package main

// The machine behind every torrent in the four collections Minerva cuts PER
// MACHINE. This is the second of the two maps minerva.go describes, and it is
// the loud one.
//
// # WHY IT IS A TABLE AND NOT A FUNCTION
//
// The names here are Minerva's, and Minerva's are No-Intro's, Redump's,
// RetroAchievements' and the T-En project's -- four naming schemes that agree
// about nothing. The same machine is "Nintendo - Super Nintendo Entertainment
// System", "RA - Super Nintendo Entertainment System" and "Nintendo - Super
// Famicom [T-En] Collection". A matcher clever enough to fold those three would
// also fold "Nintendo - Nintendo Entertainment System" into the first, because
// it is a suffix of it, and the SNES shelf would fill with NES cartridges. It
// was tried; that is exactly what it did.
//
// THE THREE VALUES, which are vimmSystems' three values:
//
//	a slug     this machine. Joins the system facet, the system= filter and
//	           the /browse category page for that machine.
//	""         Minerva has this machine and this site has no slug for it. The
//	           set is PUBLISHED, carries Minerva's own name for the machine and
//	           is findable by name; it simply takes no part in the facet,
//	           because there is no chip that could select it. 464 of the 666
//	           entries below are this, and that is the honest number: Minerva
//	           indexes PlayStation 3, Saturn, Dreamcast, Jaguar, MSX and the
//	           Vita, and systems.go knows none of them.
//	absent     FAILS THE IMPORT, naming every unknown path at once. Never a
//	           quiet skip. Minerva adds directories, and the failure mode of a
//	           silent default is that a new machine's set arrives and simply
//	           does not appear, with nothing anywhere saying why.
//
// # WHAT IS DELIBERATELY NOT FOLDED
//
// Related machines stay apart, on vimm.go's rule: "a Sega CD game is not a
// Genesis game, and a facet that answers Genesis to a Sega CD disc is a worse
// failure than one that says nothing." So PC Engine CD is not tg16, the Famicom
// Disk System is not nes, the DSi is not nds, and PlayStation 2, 3, Portable
// and Vita are not psx. Every one of those is "" rather than a near-enough
// answer.
//
// "Source Code - X" sets are "" for a different reason: they are source
// releases rather than ROM sets, and a person filtering the SNES shelf is
// looking for games.
//
// Redump's "Arcade - ..." disc sets are "" as well. The `arcade` slug on this
// site is defined by archive.org's arcade collection, which is MAME driver
// names; a 200 GB Naomi GDI set is an arcade thing but not one anything here
// can run, and putting it under the same chip as the playable MAME shelf is
// the mismatch this file exists to avoid.
//
// GENERATED, THEN READ. The table was produced by resolving all 666 real
// directory names captured from /browse/ on 2026-08-24 through systems.go's own
// lookupSystem, and every non-empty slug below was checked to exist in that
// file. It is checked in as data rather than regenerated, because it is a
// record of judgements and a regeneration would silently re-make them.
var minervaSystems = map[string]string{
	"No-Intro/ACT - Apricot PC Xi":                                                          "",
	"No-Intro/APF - Imagination Machine":                                                    "",
	"No-Intro/APF - MP-1000":                                                                "",
	"No-Intro/Acorn - Archimedes":                                                           "",
	"No-Intro/Acorn - Atom (Tapes) (Bitstream)":                                             "",
	"No-Intro/Acorn - Risc PC (Flux)":                                                       "",
	"No-Intro/Acorn RISC OS - Flash Media (Misc)":                                           "",
	"No-Intro/Amstrad - CPC (Flux)":                                                         "acpc",
	"No-Intro/Amstrad - CPC (Misc)":                                                         "acpc",
	"No-Intro/Analogue - Analogue Pocket":                                                   "",
	"No-Intro/Apple - I (Tapes)":                                                            "",
	"No-Intro/Apple - II (A2R)":                                                             "appleii",
	"No-Intro/Apple - II (WOZ)":                                                             "appleii",
	"No-Intro/Apple - II (Waveform)":                                                        "appleii",
	"No-Intro/Apple - II Plus (Flux)":                                                       "",
	"No-Intro/Apple - II Plus (WOZ)":                                                        "",
	"No-Intro/Apple - IIGS (A2R)":                                                           "apple-iigs",
	"No-Intro/Apple - IIGS (WOZ)":                                                           "apple-iigs",
	"No-Intro/Apple - IIe (A2R)":                                                            "appleii",
	"No-Intro/Apple - IIe (Kryoflux)":                                                       "appleii",
	"No-Intro/Apple - IIe (WOZ)":                                                            "appleii",
	"No-Intro/Apple - Macintosh (A2R)":                                                      "mac",
	"No-Intro/Apple - Macintosh (BETA) (Bitstreams)":                                        "mac",
	"No-Intro/Apple - Macintosh (BETA) (FluxDumps)":                                         "mac",
	"No-Intro/Apple - Macintosh (DC42)":                                                     "mac",
	"No-Intro/Apple - Macintosh (KryoFlux)":                                                 "mac",
	"No-Intro/Apple - Macintosh (Uncategorized)":                                            "mac",
	"No-Intro/Apple - Macintosh (WOZ)":                                                      "mac",
	"No-Intro/Apple-Bandai - Pippin (Floppies)":                                             "",
	"No-Intro/Arcade - PC-based":                                                            "",
	"No-Intro/Arduboy Inc - Arduboy":                                                        "",
	"No-Intro/Atari - 8-bit Family":                                                         "atari8bit",
	"No-Intro/Atari - 8-bit Family (Aftermarket)":                                           "atari8bit",
	"No-Intro/Atari - 8-bit Family (Kryoflux)":                                              "atari8bit",
	"No-Intro/Atari - Atari 2600":                                                           "atari2600",
	"No-Intro/Atari - Atari 2600 (Aftermarket)":                                             "atari2600",
	"No-Intro/Atari - Atari 2600 (BIN)":                                                     "atari2600",
	"No-Intro/Atari - Atari 2600 (Private)":                                                 "atari2600",
	"No-Intro/Atari - Atari 5200":                                                           "atari5200",
	"No-Intro/Atari - Atari 7800 (A78) (Aftermarket)":                                       "atari7800",
	"No-Intro/Atari - Atari 7800 (A78) (Private)":                                           "atari7800",
	"No-Intro/Atari - Atari 7800 (BIN)":                                                     "atari7800",
	"No-Intro/Atari - Atari 7800 (BIN) (Aftermarket)":                                       "atari7800",
	"No-Intro/Atari - Atari 7800 (BIN) (Private)":                                           "atari7800",
	"No-Intro/Atari - Atari Jaguar (ABS) (Aftermarket)":                                     "",
	"No-Intro/Atari - Atari Jaguar (COF) (Aftermarket)":                                     "",
	"No-Intro/Atari - Atari Jaguar (J64)":                                                   "",
	"No-Intro/Atari - Atari Jaguar (J64) (Aftermarket)":                                     "",
	"No-Intro/Atari - Atari Jaguar (JAG)":                                                   "",
	"No-Intro/Atari - Atari Jaguar (JAG) (Aftermarket)":                                     "",
	"No-Intro/Atari - Atari Jaguar (ROM)":                                                   "",
	"No-Intro/Atari - Atari Jaguar (ROM) (Aftermarket)":                                     "",
	"No-Intro/Atari - Atari Lynx (BLL)":                                                     "lynx",
	"No-Intro/Atari - Atari Lynx (BLL) (Aftermarket)":                                       "lynx",
	"No-Intro/Atari - Atari Lynx (LNX)":                                                     "lynx",
	"No-Intro/Atari - Atari Lynx (LNX) (Aftermarket)":                                       "lynx",
	"No-Intro/Atari - Atari Lynx (LNX) (Private)":                                           "lynx",
	"No-Intro/Atari - Atari Lynx (LYX)":                                                     "lynx",
	"No-Intro/Atari - Atari Lynx (LYX) (Aftermarket)":                                       "lynx",
	"No-Intro/Atari - Atari Lynx (LYX) (Private)":                                           "lynx",
	"No-Intro/Atari - Atari ST":                                                             "atari-st",
	"No-Intro/Atari - Atari ST (Flux)":                                                      "atari-st",
	"No-Intro/Audio CD":                                                                     "",
	"No-Intro/Audio CD - Spillover Tracks":                                                  "",
	"No-Intro/BD-Video":                                                                     "",
	"No-Intro/Bally - Astrocade":                                                            "astrocade",
	"No-Intro/Bally - Astrocade (Tapes)":                                                    "astrocade",
	"No-Intro/Bally - Astrocade (Tapes) (WAV)":                                              "astrocade",
	"No-Intro/Bandai - Design Master Denshi Mangajuku":                                      "",
	"No-Intro/Bandai - Gundam RX-78":                                                        "",
	"No-Intro/Bandai - WonderSwan":                                                          "wonderswan",
	"No-Intro/Bandai - WonderSwan Color":                                                    "wonderswan-color",
	"No-Intro/Bandai - WonderSwan Color (Aftermarket)":                                      "wonderswan-color",
	"No-Intro/Bandai Little Jammer (BIN)":                                                   "",
	"No-Intro/Bandai Little Jammer Pro (BIN)":                                               "",
	"No-Intro/Benesse - Pocket Challenge V2":                                                "",
	"No-Intro/Benesse - Pocket Challenge W":                                                 "",
	"No-Intro/Bit Corporation - Gamate":                                                     "",
	"No-Intro/Blaze Entertainment - Evercade":                                               "",
	"No-Intro/CD+G":                                                                         "",
	"No-Intro/CD-ROM":                                                                       "",
	"No-Intro/Casio - Loopy (BigEndian)":                                                    "",
	"No-Intro/Casio - Loopy (LittleEndian)":                                                 "",
	"No-Intro/Casio - PV-1000":                                                              "",
	"No-Intro/Coleco - ColecoVision":                                                        "colecovision",
	"No-Intro/Commodore - Amiga":                                                            "amiga",
	"No-Intro/Commodore - Amiga (Bitstream)":                                                "amiga",
	"No-Intro/Commodore - Amiga (Flux)":                                                     "amiga",
	"No-Intro/Commodore - Commodore 64":                                                     "c64",
	"No-Intro/Commodore - Commodore 64 (Aftermarket)":                                       "c64",
	"No-Intro/Commodore - Commodore 64 (Headerless)":                                        "c64",
	"No-Intro/Commodore - Commodore 64 (PP)":                                                "c64",
	"No-Intro/Commodore - Commodore 64 (Tapes)":                                             "c64",
	"No-Intro/Commodore - Plus-4":                                                           "",
	"No-Intro/Commodore - VIC-20":                                                           "vic-20",
	"No-Intro/DVD-Audio":                                                                    "",
	"No-Intro/DVD-ROM":                                                                      "",
	"No-Intro/DVD-Video":                                                                    "",
	"No-Intro/Digital Media Cartridge - Firecore":                                           "",
	"No-Intro/Emerson - Arcadia 2001":                                                       "arcadia-2001",
	"No-Intro/Enhanced CD":                                                                  "",
	"No-Intro/Entex - Adventure Vision":                                                     "adventure-vision",
	"No-Intro/Epoch - Game Pocket Computer":                                                 "game-pocket-computer",
	"No-Intro/Epoch - Super Cassette Vision":                                                "epoch-super-cassette-vision",
	"No-Intro/Fairchild - Channel F":                                                        "fairchild-channel-f",
	"No-Intro/Fujitsu - FM Towns (Flux)":                                                    "",
	"No-Intro/Fujitsu - FM Towns (HDM)":                                                     "",
	"No-Intro/Fujitsu - FM-7 (Bitstream)":                                                   "",
	"No-Intro/Fujitsu - FM-7 (Flux)":                                                        "",
	"No-Intro/Fujitsu - FM-7 (Sector)":                                                      "",
	"No-Intro/Fujitsu - FM-7 (Tapes) (Bitstream)":                                           "",
	"No-Intro/Fujitsu - FM-7 (Tapes) (Waveform)":                                            "",
	"No-Intro/Fujitsu - FMR50 (Flux)":                                                       "",
	"No-Intro/Fukutake Publishing - StudyBox":                                               "",
	"No-Intro/Funtech - Super Acan":                                                         "super-acan",
	"No-Intro/GCE - Vectrex":                                                                "vectrex",
	"No-Intro/GamePark - GP2X":                                                              "",
	"No-Intro/GamePark - GP32":                                                              "",
	"No-Intro/Google - Android (Amazon Appstore) (APK)":                                     "",
	"No-Intro/Google - Android (Google Play Store) (APK)":                                   "",
	"No-Intro/Google - Android (Misc) (APK)":                                                "",
	"No-Intro/Google - Android (Samsung Galaxy Apps) (APK)":                                 "",
	"No-Intro/HD DVD":                                                                       "",
	"No-Intro/Hartung - Game Master":                                                        "",
	"No-Intro/Hitachi - S1 (Waveform)":                                                      "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Amazon)":                                  "",
	"No-Intro/IBM - PC and Compatibles (Digital) (BOOTH)":                                   "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Ci-en)":                                   "",
	"No-Intro/IBM - PC and Compatibles (Digital) (DLsite)":                                  "",
	"No-Intro/IBM - PC and Compatibles (Digital) (DLsite) (Hentai)":                         "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Denpasoft)":                               "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Desura)":                                  "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Epic Games Launcher)":                     "",
	"No-Intro/IBM - PC and Compatibles (Digital) (FANZA)":                                   "",
	"No-Intro/IBM - PC and Compatibles (Digital) (FANZA) (Doujin)":                          "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Flash)":                                   "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Freem!)":                                  "",
	"No-Intro/IBM - PC and Compatibles (Digital) (GOG)":                                     "",
	"No-Intro/IBM - PC and Compatibles (Digital) (GamersGate)":                              "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Games for Windows Live)":                  "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Games for Windows Live) (Deprecated)":     "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Getchu.com)":                              "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Groupees)":                                "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Humble Bundle)":                           "",
	"No-Intro/IBM - PC and Compatibles (Digital) (JAST USA)":                                "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Johren)":                                  "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Kagura Games)":                            "",
	"No-Intro/IBM - PC and Compatibles (Digital) (MangaGamer)":                              "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Microsoft Store)":                         "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Misc)":                                    "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Misc) (Hentai)":                           "",
	"No-Intro/IBM - PC and Compatibles (Digital) (NovelGameCollection)":                     "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Press Kits)":                              "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Steam)":                                   "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Steam) (Hentai)":                          "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Unknown)":                                 "",
	"No-Intro/IBM - PC and Compatibles (Digital) (Updates and DLC)":                         "",
	"No-Intro/IBM - PC and Compatibles (Flash Media)":                                       "",
	"No-Intro/IBM - PC and Compatibles (Flux)":                                              "",
	"No-Intro/IBM - PC and Compatibles (IPF)":                                               "",
	"No-Intro/IBM - PC and Compatibles (LooseFilesArchive)":                                 "",
	"No-Intro/IBM - PC and Compatibles (SCP)":                                               "",
	"No-Intro/IBM - PC and Compatibles (Tiger Electronics - Net Jet)":                       "",
	"No-Intro/Interton - VC 4000":                                                           "",
	"No-Intro/Konami - Picno":                                                               "",
	"No-Intro/LeapFrog - Explorer":                                                          "",
	"No-Intro/LeapFrog - LeapPad":                                                           "",
	"No-Intro/LeapFrog - Leapster Learning Game System":                                     "",
	"No-Intro/Luxor - ABC 800 (Flux)":                                                       "",
	"No-Intro/MP3 CD":                                                                       "",
	"No-Intro/Magnavox - Odyssey 2":                                                         "odyssey-2",
	"No-Intro/Mattel - Intellivision":                                                       "intellivision",
	"No-Intro/Mattel - Intellivision (Aftermarket)":                                         "intellivision",
	"No-Intro/Microsoft - MSX":                                                              "",
	"No-Intro/Microsoft - MSX (Aftermarket)":                                                "",
	"No-Intro/Microsoft - MSX2":                                                             "",
	"No-Intro/Microsoft - MSX2 (Aftermarket)":                                               "",
	"No-Intro/Microsoft - Xbox (Development Kit Hard Drives)":                               "",
	"No-Intro/Microsoft - Xbox 360 (Development Kit Hard Drives)":                           "",
	"No-Intro/Microsoft - Xbox 360 (Digital)":                                               "",
	"No-Intro/Milton-Bradley - Omni (Waveform)":                                             "",
	"No-Intro/Mobile - J2ME":                                                                "",
	"No-Intro/Mobile - Palm OS":                                                             "palm",
	"No-Intro/Mobile - Palm OS (Digital)":                                                   "palm",
	"No-Intro/Mobile - Pocket PC":                                                           "",
	"No-Intro/Mobile - Pocket PC (Digital)":                                                 "",
	"No-Intro/Mobile - Symbian":                                                             "",
	"No-Intro/MovieCD":                                                                      "",
	"No-Intro/NEC - PC Engine - TurboGrafx-16":                                              "tg16",
	"No-Intro/NEC - PC Engine - TurboGrafx-16 (Aftermarket)":                                "tg16",
	"No-Intro/NEC - PC Engine - TurboGrafx-16 (Private)":                                    "tg16",
	"No-Intro/NEC - PC Engine SuperGrafx":                                                   "supergrafx",
	"No-Intro/NEC - PC Engine SuperGrafx (Aftermarket)":                                     "supergrafx",
	"No-Intro/NEC - PC-88 (Flux)":                                                           "",
	"No-Intro/NEC - PC-88 (KryoFlux)":                                                       "",
	"No-Intro/NEC - PC-98":                                                                  "",
	"No-Intro/NEC - PC-98 (Flux)":                                                           "",
	"No-Intro/NEC - PC-98 (Greaseweazle)":                                                   "",
	"No-Intro/NEC - PC-98 (HardDisk)":                                                       "",
	"No-Intro/NEC - PC-98 (Uncategorized)":                                                  "",
	"No-Intro/Nichibutsu - My Vision":                                                       "",
	"No-Intro/Nichibutsu - My Vision (Mame)":                                                "",
	"No-Intro/Nintendo - Family BASIC (Tapes)":                                              "",
	"No-Intro/Nintendo - Family Computer Disk System (FDS)":                                 "",
	"No-Intro/Nintendo - Family Computer Disk System (FDS) (Aftermarket)":                   "",
	"No-Intro/Nintendo - Family Computer Disk System (QD)":                                  "",
	"No-Intro/Nintendo - Family Computer Network System":                                    "",
	"No-Intro/Nintendo - Game & Watch":                                                      "",
	"No-Intro/Nintendo - Game Boy":                                                          "gb",
	"No-Intro/Nintendo - Game Boy (Aftermarket)":                                            "gb",
	"No-Intro/Nintendo - Game Boy (Private)":                                                "gb",
	"No-Intro/Nintendo - Game Boy Advance":                                                  "gba",
	"No-Intro/Nintendo - Game Boy Advance (Aftermarket)":                                    "gba",
	"No-Intro/Nintendo - Game Boy Advance (Multiboot)":                                      "gba",
	"No-Intro/Nintendo - Game Boy Advance (Play-Yan)":                                       "gba",
	"No-Intro/Nintendo - Game Boy Advance (Private)":                                        "gba",
	"No-Intro/Nintendo - Game Boy Advance (Video)":                                          "gba",
	"No-Intro/Nintendo - Game Boy Advance (Video) (Aftermarket)":                            "gba",
	"No-Intro/Nintendo - Game Boy Advance (Video) (Private)":                                "gba",
	"No-Intro/Nintendo - Game Boy Advance (e-Reader)":                                       "gba",
	"No-Intro/Nintendo - Game Boy Advance (e-Reader) (Aftermarket)":                         "gba",
	"No-Intro/Nintendo - Game Boy Color":                                                    "gbc",
	"No-Intro/Nintendo - Game Boy Color (Aftermarket)":                                      "gbc",
	"No-Intro/Nintendo - Game Boy Color (Private)":                                          "gbc",
	"No-Intro/Nintendo - Kiosk Video Compact Flash (CardImage)":                             "",
	"No-Intro/Nintendo - Kiosk Video Compact Flash (Extracted)":                             "",
	"No-Intro/Nintendo - Misc":                                                              "",
	"No-Intro/Nintendo - New Nintendo 3DS (Decrypted)":                                      "",
	"No-Intro/Nintendo - New Nintendo 3DS (Digital) (Deprecated)":                           "",
	"No-Intro/Nintendo - New Nintendo 3DS (Encrypted)":                                      "",
	"No-Intro/Nintendo - Nintendo 3DS (Decrypted)":                                          "",
	"No-Intro/Nintendo - Nintendo 3DS (Digital) (CDN)":                                      "",
	"No-Intro/Nintendo - Nintendo 3DS (Digital) (Deprecated)":                               "",
	"No-Intro/Nintendo - Nintendo 3DS (Digital) (Dev ROMs)":                                 "",
	"No-Intro/Nintendo - Nintendo 3DS (Digital) (Pre-Install)":                              "",
	"No-Intro/Nintendo - Nintendo 3DS (Digital) (SpotPass)":                                 "",
	"No-Intro/Nintendo - Nintendo 3DS (Encrypted)":                                          "",
	"No-Intro/Nintendo - Nintendo 64 (BigEndian)":                                           "n64",
	"No-Intro/Nintendo - Nintendo 64 (BigEndian) (Aftermarket)":                             "n64",
	"No-Intro/Nintendo - Nintendo 64 (BigEndian) (Private)":                                 "n64",
	"No-Intro/Nintendo - Nintendo 64 (ByteSwapped)":                                         "n64",
	"No-Intro/Nintendo - Nintendo 64 (ByteSwapped) (Aftermarket)":                           "n64",
	"No-Intro/Nintendo - Nintendo 64 (ByteSwapped) (Private)":                               "n64",
	"No-Intro/Nintendo - Nintendo 64 (Mario no Photopi SmartMedia)":                         "n64",
	"No-Intro/Nintendo - Nintendo 64DD":                                                     "",
	"No-Intro/Nintendo - Nintendo DS (DSvision SD cards)":                                   "nds",
	"No-Intro/Nintendo - Nintendo DS (Decrypted)":                                           "nds",
	"No-Intro/Nintendo - Nintendo DS (Decrypted) (Aftermarket)":                             "nds",
	"No-Intro/Nintendo - Nintendo DS (Decrypted) (Private)":                                 "nds",
	"No-Intro/Nintendo - Nintendo DS (Download Play)":                                       "nds",
	"No-Intro/Nintendo - Nintendo DS (Encrypted)":                                           "nds",
	"No-Intro/Nintendo - Nintendo DS (Encrypted) (Aftermarket)":                             "nds",
	"No-Intro/Nintendo - Nintendo DS (Encrypted) (Private)":                                 "nds",
	"No-Intro/Nintendo - Nintendo DSi (Decrypted)":                                          "",
	"No-Intro/Nintendo - Nintendo DSi (Digital)":                                            "",
	"No-Intro/Nintendo - Nintendo DSi (Digital) (CDN) (Decrypted)":                          "",
	"No-Intro/Nintendo - Nintendo DSi (Digital) (CDN) (Encrypted)":                          "",
	"No-Intro/Nintendo - Nintendo DSi (Encrypted)":                                          "",
	"No-Intro/Nintendo - Nintendo Entertainment System (Headered)":                          "nes",
	"No-Intro/Nintendo - Nintendo Entertainment System (Headered) (Aftermarket)":            "nes",
	"No-Intro/Nintendo - Nintendo Entertainment System (Headered) (Private)":                "nes",
	"No-Intro/Nintendo - Nintendo Entertainment System (Headerless)":                        "nes",
	"No-Intro/Nintendo - Nintendo Entertainment System (Headerless) (Aftermarket)":          "nes",
	"No-Intro/Nintendo - Nintendo Entertainment System (Headerless) (Private)":              "nes",
	"No-Intro/Nintendo - Nintendo GameCube (Memory Card)":                                   "",
	"No-Intro/Nintendo - Nintendo GameCube (NPDP Carts)":                                    "",
	"No-Intro/Nintendo - Nintendo Music (M4A)":                                              "",
	"No-Intro/Nintendo - Nintendo Music (Tracks)":                                           "",
	"No-Intro/Nintendo - Pokemon Mini":                                                      "",
	"No-Intro/Nintendo - Pokemon Mini (Aftermarket)":                                        "",
	"No-Intro/Nintendo - SDKs":                                                              "",
	"No-Intro/Nintendo - Satellaview":                                                       "",
	"No-Intro/Nintendo - Satellaview (Aftermarket)":                                         "",
	"No-Intro/Nintendo - Sufami Turbo":                                                      "",
	"No-Intro/Nintendo - Super Nintendo Entertainment System":                               "snes",
	"No-Intro/Nintendo - Super Nintendo Entertainment System (Aftermarket)":                 "snes",
	"No-Intro/Nintendo - Super Nintendo Entertainment System (Private)":                     "snes",
	"No-Intro/Nintendo - Virtual Boy":                                                       "",
	"No-Intro/Nintendo - Virtual Boy (Aftermarket)":                                         "",
	"No-Intro/Nintendo - Virtual Boy (Private)":                                             "",
	"No-Intro/Nintendo - Wallpapers":                                                        "",
	"No-Intro/Nintendo - Wii (Development Kit Hard Drives)":                                 "",
	"No-Intro/Nintendo - Wii (Digital) (CDN)":                                               "",
	"No-Intro/Nintendo - Wii (Starlight Fun Center)":                                        "",
	"No-Intro/Nintendo - Wii U (Development Kit Hard Drives)":                               "",
	"No-Intro/Nintendo - Wii U (Digital) (CDN)":                                             "",
	"No-Intro/Nintendo - Wii U (Digital) (CDN) (Dev)":                                       "",
	"No-Intro/Nintendo - Wii U (Digital) (CDN) (Lotcheck)":                                  "",
	"No-Intro/Nintendo - amiibo":                                                            "",
	"No-Intro/Nokia - N-Gage (WIP)":                                                         "",
	"No-Intro/Non-Redump - Apple-Bandai - Pippin":                                           "",
	"No-Intro/Non-Redump - Atari - Atari Jaguar CD":                                         "",
	"No-Intro/Non-Redump - Audio CD":                                                        "",
	"No-Intro/Non-Redump - BD-Video":                                                        "",
	"No-Intro/Non-Redump - Capcom - Play System III":                                        "",
	"No-Intro/Non-Redump - Commodore - Amiga CD":                                            "",
	"No-Intro/Non-Redump - DVD-Video":                                                       "",
	"No-Intro/Non-Redump - FuRyu & Omron - Purikura":                                        "",
	"No-Intro/Non-Redump - Hasbro - iON Educational Gaming System":                          "",
	"No-Intro/Non-Redump - IBM - PC Compatible (Discs)":                                     "",
	"No-Intro/Non-Redump - IBM - PC Compatible (Discs) (Hentai)":                            "",
	"No-Intro/Non-Redump - Konami - M2":                                                     "",
	"No-Intro/Non-Redump - Konami - Python 2":                                               "",
	"No-Intro/Non-Redump - Merit Megatouch":                                                 "",
	"No-Intro/Non-Redump - Microsoft - Pocket PC":                                           "",
	"No-Intro/Non-Redump - Microsoft - Xbox":                                                "",
	"No-Intro/Non-Redump - Microsoft - Xbox 360":                                            "",
	"No-Intro/Non-Redump - NEC - PC Engine CD + TurboGrafx CD":                              "",
	"No-Intro/Non-Redump - NEC - PC Engine CD + TurboGrafx CD (Aftermarket)":                "",
	"No-Intro/Non-Redump - NEC - PC-88":                                                     "",
	"No-Intro/Non-Redump - Namco - Purikura":                                                "",
	"No-Intro/Non-Redump - Nintendo - Nintendo GameCube":                                    "",
	"No-Intro/Non-Redump - Nintendo - Nintendo GameCube (Aftermarket)":                      "",
	"No-Intro/Non-Redump - Nintendo - Nintendo GameCube (Private)":                          "",
	"No-Intro/Non-Redump - Nintendo - Wii":                                                  "",
	"No-Intro/Non-Redump - Nintendo - Wii U":                                                "",
	"No-Intro/Non-Redump - Panasonic - 3DO Interactive Multiplayer":                         "",
	"No-Intro/Non-Redump - Philips - CD-i":                                                  "",
	"No-Intro/Non-Redump - Philips - CD-i (Aftermarket)":                                    "",
	"No-Intro/Non-Redump - Playmaji - Polymega":                                             "",
	"No-Intro/Non-Redump - Sega - ALLS":                                                     "",
	"No-Intro/Non-Redump - Sega - Dreamcast":                                                "",
	"No-Intro/Non-Redump - Sega - Dreamcast (Aftermarket)":                                  "",
	"No-Intro/Non-Redump - Sega - Dreamcast (Private)":                                      "",
	"No-Intro/Non-Redump - Sega - Nu":                                                       "",
	"No-Intro/Non-Redump - Sega - Nu 1.1":                                                   "",
	"No-Intro/Non-Redump - Sega - Nu 2":                                                     "",
	"No-Intro/Non-Redump - Sega - Nu SX":                                                    "",
	"No-Intro/Non-Redump - Sega - Sega Mega CD + Sega CD":                                   "",
	"No-Intro/Non-Redump - Sega - Sega Mega CD + Sega CD (Aftermarket)":                     "",
	"No-Intro/Non-Redump - Sega - Sega Saturn":                                              "",
	"No-Intro/Non-Redump - Sega NAOMI Satellite Terminal PC":                                "",
	"No-Intro/Non-Redump - Sharp - Zaurus":                                                  "",
	"No-Intro/Non-Redump - Sony - PlayStation":                                              "psx",
	"No-Intro/Non-Redump - Sony - PlayStation 2":                                            "",
	"No-Intro/Non-Redump - Sony - PlayStation 3":                                            "",
	"No-Intro/Non-Redump - Sony - PlayStation Portable":                                     "",
	"No-Intro/Non-Redump - Sony Electronic Book":                                            "",
	"No-Intro/Non-Redump - VM Labs - NUON":                                                  "",
	"No-Intro/Non-Redump - ZAPiT Games - Game Wave Family Entertainment System":             "",
	"No-Intro/Ouya - Ouya":                                                                  "",
	"No-Intro/Panic - Playdate (Catalog) (Decrypted)":                                       "",
	"No-Intro/Panic - Playdate (Catalog) (Encrypted)":                                       "",
	"No-Intro/Panic - Playdate (Various)":                                                   "",
	"No-Intro/Panic - Playdate (itch.io)":                                                   "",
	"No-Intro/Philips - Videopac+":                                                          "",
	"No-Intro/Project EGG":                                                                  "",
	"No-Intro/RCA - Studio II":                                                              "",
	"No-Intro/SACD":                                                                         "",
	"No-Intro/SNK - NeoGeo Pocket":                                                          "neo-geo-pocket",
	"No-Intro/SNK - NeoGeo Pocket Color":                                                    "neo-geo-pocket-color",
	"No-Intro/Sanyo - MBC-550 (Flux)":                                                       "",
	"No-Intro/Sega - 32X":                                                                   "sega32",
	"No-Intro/Sega - 32X (Aftermarket)":                                                     "sega32",
	"No-Intro/Sega - Beena":                                                                 "",
	"No-Intro/Sega - Dreamcast (Development Kit Hard Drives)":                               "",
	"No-Intro/Sega - Dreamcast (Visual Memory Unit)":                                        "",
	"No-Intro/Sega - Game Gear":                                                             "gamegear",
	"No-Intro/Sega - Game Gear (Aftermarket)":                                               "gamegear",
	"No-Intro/Sega - Master System - Mark III":                                              "sms",
	"No-Intro/Sega - Master System - Mark III (Aftermarket)":                                "sms",
	"No-Intro/Sega - Master System - Mark III (Private)":                                    "sms",
	"No-Intro/Sega - Mega Drive - Genesis":                                                  "genesis",
	"No-Intro/Sega - Mega Drive - Genesis (Aftermarket)":                                    "genesis",
	"No-Intro/Sega - Mega Drive - Genesis (Private)":                                        "genesis",
	"No-Intro/Sega - PICO":                                                                  "",
	"No-Intro/Sega - SG-1000":                                                               "sg1000",
	"No-Intro/Sega - SG-1000 - SC-3000":                                                     "sg1000",
	"No-Intro/Sega - SG-1000 - SC-3000 (Aftermarket)":                                       "sg1000",
	"No-Intro/Seta - Aleck64 (BigEndian)":                                                   "",
	"No-Intro/Seta - Aleck64 (ByteSwapped)":                                                 "",
	"No-Intro/Sharp - MZ-2200 (Waveform)":                                                   "",
	"No-Intro/Sharp - MZ-700 (Waveform)":                                                    "",
	"No-Intro/Sharp - X1 (Waveform)":                                                        "",
	"No-Intro/Sharp - X68000 (Flux)":                                                        "",
	"No-Intro/Sinclair - ZX Spectrum +3":                                                    "zxs",
	"No-Intro/Sony - PlayStation (PS one Classics) (PSN)":                                   "psx",
	"No-Intro/Sony - PlayStation 3 (Development Kit Hard Drives) (Decrypted)":               "",
	"No-Intro/Sony - PlayStation 3 (PSN) (Avatars)":                                         "",
	"No-Intro/Sony - PlayStation 3 (PSN) (Content)":                                         "",
	"No-Intro/Sony - PlayStation 3 (PSN) (DLC)":                                             "",
	"No-Intro/Sony - PlayStation 3 (PSN) (Themes)":                                          "",
	"No-Intro/Sony - PlayStation 3 (PSN) (Updates)":                                         "",
	"No-Intro/Sony - PlayStation Mobile (PSN)":                                              "",
	"No-Intro/Sony - PlayStation Portable (PSN) (Decrypted)":                                "",
	"No-Intro/Sony - PlayStation Portable (PSN) (Encrypted)":                                "",
	"No-Intro/Sony - PlayStation Portable (PSN) (Minis) (Decrypted)":                        "",
	"No-Intro/Sony - PlayStation Portable (PSN) (Minis) (Encrypted)":                        "",
	"No-Intro/Sony - PlayStation Vita (PSN) (Content)":                                      "",
	"No-Intro/Sony - PlayStation Vita (PSN) (Updates)":                                      "",
	"No-Intro/Source Code - Apple - II":                                                     "",
	"No-Intro/Source Code - Apple - IIGS":                                                   "",
	"No-Intro/Source Code - Arcade":                                                         "",
	"No-Intro/Source Code - Atari - 2600":                                                   "",
	"No-Intro/Source Code - Atari - 8-bit Family":                                           "",
	"No-Intro/Source Code - Atari - Atari 2600 (Aftermarket)":                               "",
	"No-Intro/Source Code - IBM - PC and Compatibles":                                       "",
	"No-Intro/Source Code - Mobile - Palm OS":                                               "",
	"No-Intro/Source Code - Nintendo - Game Boy Advance":                                    "",
	"No-Intro/Source Code - Nintendo - Game Boy Color":                                      "",
	"No-Intro/Source Code - Nintendo - Nintendo - Game Boy Color":                           "",
	"No-Intro/Source Code - Nintendo - Nintendo DS":                                         "",
	"No-Intro/Source Code - Nintendo - Nintendo Entertainment System":                       "",
	"No-Intro/Source Code - Nintendo - Nintendo GameCube":                                   "",
	"No-Intro/Source Code - Nintendo - Super Nintendo Entertainment System":                 "",
	"No-Intro/Source Code - Panasonic - 3DO Interactive Multiplayer":                        "",
	"No-Intro/Source Code - Panasonic - M2":                                                 "",
	"No-Intro/Source Code - Sega - DreamCast":                                               "",
	"No-Intro/Source Code - VM Labs - NUON":                                                 "",
	"No-Intro/Source Code - Various":                                                        "",
	"No-Intro/TEMP IBM - PC and Compatibles (Digital) (Games for Windows Marketplace)":      "",
	"No-Intro/TeleNova - Compis (Flux)":                                                     "",
	"No-Intro/Texas Instruments - TI-99-4A (A2R)":                                           "",
	"No-Intro/Tiger - Game.com":                                                             "game-dot-com",
	"No-Intro/Tiger - Gizmondo":                                                             "",
	"No-Intro/Toshiba - Pasopia (BIN)":                                                      "",
	"No-Intro/Toshiba - Pasopia (WAV)":                                                      "",
	"No-Intro/Toshiba - Visicom":                                                            "",
	"No-Intro/UHD-BD":                                                                       "",
	"No-Intro/Unofficial - Microsoft - Xbox 360 (Title Updates)":                            "",
	"No-Intro/Unofficial - Nintendo - Nintendo 3DS (Digital) (Updates and DLC) (Decrypted)": "",
	"No-Intro/Unofficial - Nintendo - Nintendo 3DS (Digital) (Updates and DLC) (Encrypted)": "",
	"No-Intro/Unofficial - Nintendo - Wii (Digital) (Deprecated) (WAD)":                     "",
	"No-Intro/Unofficial - Nintendo - Wii (Digital) (Split DLC) (Deprecated) (WAD)":         "",
	"No-Intro/Unofficial - Nintendo - Wii U (Digital) (Deprecated)":                         "",
	"No-Intro/Unofficial - Obscure Gamers":                                                  "",
	"No-Intro/Unofficial - Sony - PlayStation 3 (BD-Video Extras)":                          "",
	"No-Intro/Unofficial - Sony - PlayStation 3 (PSN) (Decrypted)":                          "",
	"No-Intro/Unofficial - Sony - PlayStation Portable (PSN) (Decrypted)":                   "",
	"No-Intro/Unofficial - Sony - PlayStation Portable (PSX2PSP)":                           "",
	"No-Intro/Unofficial - Sony - PlayStation Portable (UMD Music)":                         "",
	"No-Intro/Unofficial - Sony - PlayStation Portable (UMD Video)":                         "",
	"No-Intro/Unofficial - Sony - PlayStation Vita (BlackFinPSV)":                           "",
	"No-Intro/Unofficial - Sony - PlayStation Vita (NoNpDrm)":                               "",
	"No-Intro/Unofficial - Sony - PlayStation Vita (PSN) (Decrypted) (NoNpDrm)":             "",
	"No-Intro/Unofficial - Sony - PlayStation Vita (PSN) (Decrypted) (VPK)":                 "",
	"No-Intro/Unofficial - Sony - PlayStation Vita (PSVgameSD)":                             "",
	"No-Intro/Unofficial - Sony - PlayStation Vita (VPK)":                                   "",
	"No-Intro/Unofficial - Super Mario Maker Courses (WARC)":                                "",
	"No-Intro/Unofficial - Video Game Documents (PDF)":                                      "",
	"No-Intro/Unofficial - Video Game Magazine Scans (CBZ)":                                 "",
	"No-Intro/Unofficial - Video Game Magazine Scans (PDF)":                                 "",
	"No-Intro/Unofficial - Video Game Magazine Scans (RAW)":                                 "",
	"No-Intro/Unofficial - Video Game Manual Scans (JPEG)":                                  "",
	"No-Intro/Unofficial - Video Game OSTs (Digital) (RAW)":                                 "",
	"No-Intro/Unofficial - Video Game OSTs (Hardware Recordings)":                           "",
	"No-Intro/Unofficial - Video Game OSTs (Playbutton)":                                    "",
	"No-Intro/Unofficial - Video Game Scans (RAW)":                                          "",
	"No-Intro/VM Labs - NUON (Digital)":                                                     "",
	"No-Intro/VTech - CreatiVision":                                                         "creativision",
	"No-Intro/VTech - V.Smile":                                                              "",
	"No-Intro/Various - itch.io":                                                            "",
	"No-Intro/Video CD":                                                                     "",
	"No-Intro/Watara - Supervision":                                                         "supervision",
	"No-Intro/Watara - Supervision (Aftermarket)":                                           "supervision",
	"No-Intro/Watara - Supervision (Private)":                                               "supervision",
	"No-Intro/Web - Humble Play":                                                            "",
	"No-Intro/Welback - Mega Duck":                                                          "mega-duck-slash-cougar-boy",
	"No-Intro/Welback - Mega Duck (Aftermarket)":                                            "mega-duck-slash-cougar-boy",
	"No-Intro/Yamaha - Copera":                                                              "",
	"No-Intro/Zeebo - Zeebo":                                                                "",
	"No-Intro/iQue - iQue (CDN)":                                                            "",
	"No-Intro/iQue - iQue (Decrypted)":                                                      "",
	"Redump/Acorn - Archimedes":                                                             "",
	"Redump/Apple - Macintosh":                                                              "mac",
	"Redump/Apple - Macintosh - SBI Subchannels":                                            "mac",
	"Redump/Arcade":                                                             "arcade",
	"Redump/Arcade - Hasbro - VideoNow":                                         "",
	"Redump/Arcade - Hasbro - VideoNow Color":                                   "",
	"Redump/Arcade - Hasbro - VideoNow Jr":                                      "",
	"Redump/Arcade - Hasbro - VideoNow XP":                                      "",
	"Redump/Arcade - Konami - FireBeat":                                         "",
	"Redump/Arcade - Konami - M2":                                               "",
	"Redump/Arcade - Konami - System 573":                                       "",
	"Redump/Arcade - Konami - System GV":                                        "",
	"Redump/Arcade - Konami - e-Amusement":                                      "",
	"Redump/Arcade - Namco - Sega - Nintendo - Triforce":                        "",
	"Redump/Arcade - Namco - Sega - Nintendo - Triforce - GDI Files":            "",
	"Redump/Arcade - Namco - System 246":                                        "",
	"Redump/Arcade - Sega - Chihiro":                                            "",
	"Redump/Arcade - Sega - Chihiro - GDI Files":                                "",
	"Redump/Arcade - Sega - Lindbergh":                                          "",
	"Redump/Arcade - Sega - Naomi":                                              "",
	"Redump/Arcade - Sega - Naomi - GDI Files":                                  "",
	"Redump/Arcade - Sega - Naomi 2":                                            "",
	"Redump/Arcade - Sega - Naomi 2 - GDI Files":                                "",
	"Redump/Arcade - Sega - RingEdge":                                           "",
	"Redump/Arcade - Sega - RingEdge 2":                                         "",
	"Redump/Atari - Jaguar CD Interactive Multimedia System":                    "",
	"Redump/Audio CD":                                                           "",
	"Redump/Audio CD - Spillover Tracks":                                        "",
	"Redump/BD-Video":                                                           "",
	"Redump/Bandai - Pippin":                                                    "",
	"Redump/Bandai - Playdia Quick Interactive System":                          "",
	"Redump/Commodore - Amiga CD":                                               "",
	"Redump/Commodore - Amiga CD32":                                             "",
	"Redump/Commodore - Amiga CDTV":                                             "",
	"Redump/DVD-Video":                                                          "",
	"Redump/Fujitsu - FM-Towns":                                                 "",
	"Redump/HD DVD-Video":                                                       "",
	"Redump/IBM - PC compatible":                                                "",
	"Redump/IBM - PC compatible - SBI Subchannels":                              "",
	"Redump/Incredible Technologies - Eagle":                                    "",
	"Redump/Mattel - Fisher-Price iXL":                                          "",
	"Redump/Mattel - HyperScan":                                                 "",
	"Redump/Memorex - Visual Information System":                                "",
	"Redump/Microsoft - Xbox":                                                   "",
	"Redump/Microsoft - Xbox - BIOS Images":                                     "",
	"Redump/Microsoft - Xbox - BIOS Images (DoM Version)":                       "",
	"Redump/Microsoft - Xbox 360":                                               "",
	"Redump/NEC - PC Engine CD & TurboGrafx CD":                                 "",
	"Redump/NEC - PC-88 series":                                                 "",
	"Redump/NEC - PC-98 series":                                                 "",
	"Redump/NEC - PC-FX & PC-FXGA":                                              "",
	"Redump/Navisoft - Naviken 2.1":                                             "",
	"Redump/Nintendo - GameCube - BIOS Images":                                  "",
	"Redump/Nintendo - GameCube - BIOS Images (DoM Version)":                    "",
	"Redump/Nintendo - GameCube - NKit RVZ [zstd-19-128k]":                      "",
	"Redump/Nintendo - Wii - NKit RVZ [zstd-19-128k]":                           "",
	"Redump/Nintendo - Wii U - Disc Keys":                                       "",
	"Redump/Nintendo - Wii U - WUX":                                             "",
	"Redump/Palm":                                                               "palm",
	"Redump/Panasonic - 3DO Interactive Multiplayer":                            "",
	"Redump/Panasonic - M2":                                                     "",
	"Redump/Philips - CD-i":                                                     "",
	"Redump/Photo CD":                                                           "",
	"Redump/PlayStation GameShark Updates":                                      "",
	"Redump/Pocket PC":                                                          "",
	"Redump/SNK - Neo Geo CD":                                                   "",
	"Redump/Sega - Dreamcast":                                                   "",
	"Redump/Sega - Dreamcast - GDI Files":                                       "",
	"Redump/Sega - Mega CD & Sega CD":                                           "",
	"Redump/Sega - Prologue 21":                                                 "",
	"Redump/Sega - Saturn":                                                      "",
	"Redump/Sharp - X68000":                                                     "",
	"Redump/Sony - PlayStation":                                                 "psx",
	"Redump/Sony - PlayStation - BIOS Images":                                   "psx",
	"Redump/Sony - PlayStation - BIOS Images (DoM Version)":                     "psx",
	"Redump/Sony - PlayStation - SBI Subchannels":                               "psx",
	"Redump/Sony - PlayStation 2":                                               "",
	"Redump/Sony - PlayStation 2 - BIOS Images":                                 "",
	"Redump/Sony - PlayStation 3":                                               "",
	"Redump/Sony - PlayStation 3 - Disc Keys":                                   "",
	"Redump/Sony - PlayStation 3 - Disc Keys TXT":                               "",
	"Redump/Sony - PlayStation Portable":                                        "",
	"Redump/TAB-Austria - Quizard":                                              "",
	"Redump/Tomy - Kiss-Site":                                                   "",
	"Redump/VM Labs - NUON":                                                     "",
	"Redump/VTech - V.Flash & V.Smile Pro":                                      "",
	"Redump/Video CD":                                                           "",
	"Redump/ZAPiT Games - Game Wave Family Entertainment System":                "",
	"Redump/funworld - Photo Play":                                              "",
	"RetroAchievements/RA - 3DO Interactive Multiplayer":                        "",
	"RetroAchievements/RA - Amstrad CPC":                                        "acpc",
	"RetroAchievements/RA - Apple II":                                           "appleii",
	"RetroAchievements/RA - Arcade":                                             "arcade",
	"RetroAchievements/RA - Arduboy":                                            "",
	"RetroAchievements/RA - Atari 2600":                                         "atari2600",
	"RetroAchievements/RA - Atari 7800":                                         "atari7800",
	"RetroAchievements/RA - Atari Jaguar":                                       "",
	"RetroAchievements/RA - Atari Jaguar CD":                                    "",
	"RetroAchievements/RA - Atari Lynx":                                         "lynx",
	"RetroAchievements/RA - Colecovision":                                       "colecovision",
	"RetroAchievements/RA - Elektor TV Games Computer":                          "",
	"RetroAchievements/RA - Emerson Arcadia 2001":                               "arcadia-2001",
	"RetroAchievements/RA - Fairchild Channel F":                                "fairchild-channel-f",
	"RetroAchievements/RA - GCE Vectrex":                                        "vectrex",
	"RetroAchievements/RA - Interton VC 4000":                                   "",
	"RetroAchievements/RA - Magnavox Odyssey 2":                                 "odyssey-2",
	"RetroAchievements/RA - Mattel Intellivision":                               "intellivision",
	"RetroAchievements/RA - Mega Duck":                                          "mega-duck-slash-cougar-boy",
	"RetroAchievements/RA - Microsoft MSX":                                      "",
	"RetroAchievements/RA - NEC PC-8801":                                        "",
	"RetroAchievements/RA - NEC PC-FX":                                          "",
	"RetroAchievements/RA - NEC TurboGrafx-16":                                  "tg16",
	"RetroAchievements/RA - NEC TurboGrafx-CD":                                  "",
	"RetroAchievements/RA - Nintendo 64":                                        "n64",
	"RetroAchievements/RA - Nintendo DS":                                        "nds",
	"RetroAchievements/RA - Nintendo DSi":                                       "",
	"RetroAchievements/RA - Nintendo Entertainment System":                      "nes",
	"RetroAchievements/RA - Nintendo Famicom Disk System":                       "",
	"RetroAchievements/RA - Nintendo Game Boy":                                  "gb",
	"RetroAchievements/RA - Nintendo Game Boy Advance":                          "gba",
	"RetroAchievements/RA - Nintendo Game Boy Color":                            "gbc",
	"RetroAchievements/RA - Nintendo GameCube":                                  "",
	"RetroAchievements/RA - Nintendo Pokemon Mini":                              "",
	"RetroAchievements/RA - Nintendo Virtual Boy":                               "",
	"RetroAchievements/RA - SNK Neo Geo CD":                                     "",
	"RetroAchievements/RA - SNK Neo Geo Pocket":                                 "neo-geo-pocket",
	"RetroAchievements/RA - Sega 32X":                                           "sega32",
	"RetroAchievements/RA - Sega CD":                                            "",
	"RetroAchievements/RA - Sega Dreamcast":                                     "",
	"RetroAchievements/RA - Sega Game Gear":                                     "gamegear",
	"RetroAchievements/RA - Sega Genesis":                                       "genesis",
	"RetroAchievements/RA - Sega Master System":                                 "sms",
	"RetroAchievements/RA - Sega SG-1000":                                       "sg1000",
	"RetroAchievements/RA - Sega Saturn":                                        "",
	"RetroAchievements/RA - Sony PSP":                                           "",
	"RetroAchievements/RA - Sony Playstation":                                   "psx",
	"RetroAchievements/RA - Sony Playstation 2":                                 "",
	"RetroAchievements/RA - Super Nintendo Entertainment System":                "snes",
	"RetroAchievements/RA - Uzebox":                                             "",
	"RetroAchievements/RA - WASM-4":                                             "",
	"RetroAchievements/RA - Watara Supervision":                                 "supervision",
	"RetroAchievements/RA - WonderSwan":                                         "wonderswan",
	"T-En Collection/Bandai - WonderSwan Color [T-En] Collection":               "wonderswan-color",
	"T-En Collection/Bandai - WonderSwan [T-En] Collection":                     "wonderswan",
	"T-En Collection/Casio - Loopy [T-En] Collection":                           "",
	"T-En Collection/Fujitsu - FM-Towns [T-En] Collection":                      "",
	"T-En Collection/Microsoft - MSX Turbo-R [T-En] Collection":                 "",
	"T-En Collection/Microsoft - MSX [T-En] Collection":                         "",
	"T-En Collection/Microsoft - MSX2 [T-En] Collection":                        "",
	"T-En Collection/Microsoft - XBOX 360 [T-En] Collection":                    "",
	"T-En Collection/Microsoft - XBOX [T-En] Collection":                        "",
	"T-En Collection/Mobile - J2ME [T-En] Collection":                           "",
	"T-En Collection/NEC - PC Engine CD [T-En] Collection":                      "",
	"T-En Collection/NEC - PC Engine [T-En] Collection":                         "tg16",
	"T-En Collection/NEC - PC-6001 [T-En] Collection":                           "",
	"T-En Collection/NEC - PC-8001 [T-En] Collection":                           "",
	"T-En Collection/NEC - PC-8801 [T-En] Collection":                           "",
	"T-En Collection/NEC - PC-9801 [T-En] Collection":                           "",
	"T-En Collection/NEC - PC-FX [T-En] Collection":                             "",
	"T-En Collection/Nintendo - Famicom [T-En] Collection":                      "nes",
	"T-En Collection/Nintendo - Family Computer Disk System [T-En] Collection":  "",
	"T-En Collection/Nintendo - Game Boy Advance [T-En] Collection":             "gba",
	"T-En Collection/Nintendo - Game Boy Color [T-En] Collection":               "gbc",
	"T-En Collection/Nintendo - Game Boy [T-En] Collection":                     "gb",
	"T-En Collection/Nintendo - GameCube [T-En] Collection":                     "",
	"T-En Collection/Nintendo - Nintendo 3DS [T-En] Collection":                 "",
	"T-En Collection/Nintendo - Nintendo 64 [T-En] Collection":                  "n64",
	"T-En Collection/Nintendo - Nintendo 64DD [T-En] Collection":                "",
	"T-En Collection/Nintendo - Nintendo DS [T-En] Collection":                  "nds",
	"T-En Collection/Nintendo - Nintendo DSi [T-En] Collection":                 "",
	"T-En Collection/Nintendo - Pokemon Mini [T-En] Collection":                 "",
	"T-En Collection/Nintendo - Super Famicom - Enhanced Colors":                "snes",
	"T-En Collection/Nintendo - Super Famicom - MSU1":                           "snes",
	"T-En Collection/Nintendo - Super Famicom - MSU1 [roms only]":               "snes",
	"T-En Collection/Nintendo - Super Famicom - Speed Hacks":                    "snes",
	"T-En Collection/Nintendo - Super Famicom [T-En] Collection":                "snes",
	"T-En Collection/Nintendo - Virtual Boy [T-En] Collection":                  "",
	"T-En Collection/Nintendo - Wii [T-En] Collection":                          "",
	"T-En Collection/Nokia - N-Gage [T-En] Collection":                          "",
	"T-En Collection/Panasonic - 3DO Interactive Multiplayer [T-En] Collection": "",
	"T-En Collection/SNK - Neo Geo CD [T-En] Collection":                        "",
	"T-En Collection/SNK - Neo Geo Pocket Color [T-En] Collection":              "neo-geo-pocket-color",
	"T-En Collection/Sega - 32X - MD+":                                          "sega32",
	"T-En Collection/Sega - 32X - MSU-MD":                                       "sega32",
	"T-En Collection/Sega - Dreamcast [T-En] Collection":                        "",
	"T-En Collection/Sega - Game Gear [T-En] Collection":                        "gamegear",
	"T-En Collection/Sega - Master System [T-En] Collection":                    "sms",
	"T-En Collection/Sega - Mega CD Hacks":                                      "",
	"T-En Collection/Sega - Mega CD [T-En] Collection":                          "",
	"T-En Collection/Sega - Mega Drive - Enhanced Colors":                       "genesis",
	"T-En Collection/Sega - Mega Drive - MD+":                                   "genesis",
	"T-En Collection/Sega - Mega Drive - MSU-MD":                                "genesis",
	"T-En Collection/Sega - Mega Drive - Mode 1 CD":                             "genesis",
	"T-En Collection/Sega - Mega Drive [T-En] Collection":                       "genesis",
	"T-En Collection/Sega - SG-1000 [T-En] Collection":                          "sg1000",
	"T-En Collection/Sega - Saturn [T-En] Collection":                           "",
	"T-En Collection/Sharp - X1 [T-En] Collection":                              "",
	"T-En Collection/Sharp - X68000 [T-En] Collection":                          "",
	"T-En Collection/Sony - PlayStation 2 [T-En] Collection":                    "",
	"T-En Collection/Sony - PlayStation 3 [T-En] Collection":                    "",
	"T-En Collection/Sony - PlayStation Portable [T-En] Collection":             "",
	"T-En Collection/Sony - PlayStation [T-En] Collection":                      "psx",
	"T-En Collection/Zeebo - Zeebo [T-En] Collection":                           "",
}
