package main

// Turning an archive.org item into an honest Play button.
//
// Yarr.It could already FIND games on archive.org (archive.go) and could
// already run one in EmulatorJS once a person pressed Play
// (web/src/resolvers/archive.js). What was missing is the thing in between:
// deciding, BEFORE the button is drawn, whether pressing it will actually
// produce a game. Today that decision is made twice -- once in archive.go's
// `ejsCores` and once in the browser's `IA_TO_EJS` -- and neither copy knows
// any of the four things that actually stop a game from playing.
//
// Measured against live archive.org on 2026-08-07, the shipped decision offers
// EmulatorJS for:
//
//     gamegear   602 items,  22 downloadable   (96% are stream-only)
//     a7800      739 items,  28 downloadable
//     lynx        97 items,   2 downloadable
//     psx      2,740 items, 148 downloadable   (and those are ~450 MB .chd)
//     coleco     266 items,  32 downloadable   (and every one needs a BIOS)
//
// Every other item in those five systems is a Play button that cannot work.
// That is what this file exists to stop.
//
// THE RULE: only offer Play when it will actually play. Where it will not, the
// API says which of the reasons applies, in words a UI can show, and -- when
// the Internet Archive's own player can still run it -- routes there instead.
// A refusal that names an alternative is not a dead end.
//
// ---------------------------------------------------------------------------
// WHY THIS IS GO HERE AND NOT A ROM HUB PLUGIN
// ---------------------------------------------------------------------------
//
// ROM Hub is ROMarr's plugin factory, and the archive.org plugin it already
// ships is right and is reused rather than reimplemented -- see the two tables
// below, both of which are its work. But a ROM Hub plugin cannot be the answer
// to this particular question, for reasons that are structural rather than
// preference:
//
//   * A plugin never talks to a library server and returns a DESCRIPTION of
//     work for the Hub to execute. The playability verdict is not a plugin
//     concern at all -- in ROM Hub it lives in the host, `rom_hub/playability.py`.
//   * The Hub is a Python sidecar that an operator installs beside their own
//     library server, with a seccomp-confined subprocess per plugin. A Yarr.It
//     visitor is an anonymous browser hitting a Go binary on a VPS. There is no
//     Hub in that path and putting one there would mean every visitor needs the
//     thing this work exists to remove.
//   * The plugin's `stream` capability already answers the question it is
//     entitled to answer -- "resolve this item to something that plays" -- and
//     answers it by returning the Archive's own details page. That is correct
//     for the Hub and is exactly the `routeArchive` branch below.
//
// So: the KNOWLEDGE comes from ROM Hub (and drift is caught by a test that
// reads its tables), and the DECISION runs at the edge, per request, for a
// visitor who installs nothing.
//
// ---------------------------------------------------------------------------
// WHY THERE IS A CORE MAP HERE WHEN provider_romm.go REFUSED TO KEEP ONE
// ---------------------------------------------------------------------------
//
// provider_romm.go deliberately does not copy RomM's 81-platform core map,
// because RomM's own player page answers the per-platform question and a second
// copy could only drift from it. That reasoning does not transfer, because here
// there is nobody to ask:
//
//   * archive.org knows nothing about EmulatorJS. Its `emulator` field is its
//     own emulator id (`megadriv`, `a2600p`, `vice-resid`).
//   * There is no RomM in this path. The visitor runs nothing.
//
// Somebody has to hold the translation, so the honest question is not whether
// to have a table but how to keep it true. Three defences, all of them tests
// rather than intentions (see play_archive_test.go):
//
//   1. Every core value must be one of the 36 systems EmulatorJS's own
//      `getCores()` defines. This is the guard for the trap that cost a real
//      library 1,451 games: `gbc`, `pcecd`, `vice_x64` and `mame2003` all look
//      like core names and none of them exists.
//   2. Every platform slug must be one ROM Hub's `playability.EJS_CORES` also
//      considers playable. If ROM Hub says a platform is catalogue-only and we
//      offer Play for it, one of the two is wrong and the test says so.
//   3. Every archive.org emulator id must be one ROM Hub's archive-org plugin
//      maps, so this table can never quietly learn an id the plugin refuses.
//
// The table is NOT generated by composing those two, and that is deliberate: it
// was tried, and composing through libretro core names is ambiguous in exactly
// the dangerous direction. `genesis_plus_gx` and `picodrive` each appear under
// several EmulatorJS systems, so a mechanical join resolves `genesis`,
// `megadriv`, `32x`, `sms` and `gamegear` all to `segaMS` -- a Mega Drive game
// booted as a Master System, which is the failure that boots happily and then
// runs nothing. The composition is a cross-check, never a generator.

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"sort"
	"strings"
	"time"
)

// How long the one metadata call gets. This endpoint paints a button, so it
// must fail fast: an Archive that is slow costs a Play button, not a page.
const playMetadataTimeout = 12 * time.Second

// The largest ROM worth relaying, matching MAX_RELAY_ROM in
// web/src/resolvers/archive.js. archive.org sends no Access-Control-Allow-Origin
// on downloads and a WASM emulator fetches the ROM itself, so every byte crosses
// our relay -- whose monthly allowance is shared with a mail server. Cartridge
// games are kilobytes to a few megabytes; anything past this is a disc image,
// which their own player streams and ours would have to pull in full.
//
// It is enforced HERE as well as in the browser on purpose. Enforced only in the
// browser it is a message shown after the click, which is the dead button this
// file exists to remove.
const maxRelayROMBytes = 48 << 20

// --- the vocabulary --------------------------------------------------------

// playRoute is how a caller is told to start the game. Three values, and they
// are not a quality ranking: `archive` is a real, working, in-browser game.
const (
	// Our own EmulatorJS, ROM relayed through the bridge. Touch controls, our
	// own chrome, and we pay for the bytes.
	routeEmulatorJS = "emulatorjs"
	// The Internet Archive's own Emularity player, in an iframe. Costs us
	// nothing, they pick the core, and it genuinely plays -- but it expects a
	// keyboard, so on a phone a console game there is something you can watch
	// and not play.
	routeArchive = "archive"
	// Nothing plays this. `reasons` says why.
	routeNone = "none"
)

// Refusal codes. A code rather than only a sentence because a client may want
// to style or group them, and because a test can assert on a code where prose
// would make the test a spellchecker.
const (
	reasonNotFound       = "not_found"
	reasonUpstream       = "upstream"
	reasonNotEmulated    = "not_emulated"
	reasonNoCore         = "no_core"
	reasonNeedsBIOS      = "needs_bios"
	reasonNeedsIsolation = "needs_isolation"
	reasonStreamOnly     = "stream_only"
	reasonNoPayload      = "no_payload"
	reasonTooLarge       = "too_large"
)

// --- what EmulatorJS can be asked to run -----------------------------------

// emulatorJSSystems is `getCores()` out of EmulatorJS's own emulator.min.js,
// read from https://cdn.emulatorjs.org/stable/data/emulator.min.js on
// 2026-08-07. The value is the libretro core EmulatorJS downloads first for
// that system, which is what makes the "is the core actually published"
// question answerable rather than assumed.
//
// This exists to make a typo impossible. Four plausible-looking system names
// -- `gbc`, `pcecd`, `vice_x64`, `mame2003` -- are not in this list, and a
// table that used one of them would browse normally and fail only when somebody
// pressed Play.
var emulatorJSSystems = map[string]string{
	"3do": "opera", "amiga": "puae", "arcade": "fbneo",
	"atari2600": "stella2014", "atari5200": "a5200", "atari7800": "prosystem",
	"c128": "vice_x128", "c64": "vice_x64sc", "coleco": "gearcoleco",
	"dos": "dosbox_pure", "gb": "gambatte", "gba": "mgba",
	"jaguar": "virtualjaguar", "lynx": "handy", "mame": "mame2003_plus",
	"n64": "mupen64plus_next", "nds": "melonds", "nes": "fceumm",
	"ngp": "mednafen_ngp", "pce": "mednafen_pce", "pcfx": "mednafen_pcfx",
	"pet": "vice_xpet", "plus4": "vice_xplus4", "psp": "ppsspp",
	"psx": "pcsx_rearmed", "sega": "genesis_plus_gx", "sega32x": "picodrive",
	"segaCD": "genesis_plus_gx", "segaGG": "genesis_plus_gx",
	"segaMD": "genesis_plus_gx", "segaMS": "smsplus",
	"segaSaturn": "yabause", "snes": "snes9x", "vb": "beetle_vb",
	"vic20": "vice_xvic", "ws": "mednafen_wswan",
}

// blockedSystems are EmulatorJS systems that will not produce a game in an
// ordinary browser tab, whatever the item is. Each value is the sentence a
// person reads, and each was checked against a primary source rather than
// reasoned about, because the failure mode here is silent: a core with no BIOS
// launches, draws its own error screen, and reports itself as started.
//
// Sources, all read 2026-08-07:
//
//   - libretro's published core info files
//     (raw.githubusercontent.com/libretro/libretro-super/master/dist/info/).
//     `firmware<N>_opt = "false"` means that firmware is REQUIRED. Checked for
//     every core reachable from the table below; only the three named here have
//     one. Everything else is `"true"` (optional) or declares no firmware at
//     all -- notably `handy` (Lynx), `prosystem` (7800), `mgba`, `gambatte`,
//     `fceumm`, `snes9x`, `genesis_plus_gx` and `vice_x64sc`, all of which run
//     with no BIOS, so none of them is refused here.
//   - the EmulatorJS CDN itself, probed for the core file EmulatorJS would
//     actually request.
var blockedSystems = map[string]blockedSystem{
	"coleco": {
		Reason: reasonNeedsBIOS,
		Detail: "ColecoVision games need the console's BIOS. EmulatorJS runs " +
			"them on gearcoleco, whose core info marks colecovision.rom as " +
			"required, and console firmware is not ours to ship. Without it " +
			"the emulator starts, draws its own error screen and never boots " +
			"the game.",
	},
	"psx": {
		Reason: reasonNeedsBIOS,
		Detail: "PlayStation games need a console BIOS that is not ours to " +
			"ship, and the Internet Archive's PlayStation items are disc " +
			"images of several hundred megabytes besides.",
	},
	"amiga": {
		Reason: reasonNeedsBIOS,
		Detail: "Amiga software needs a Kickstart ROM, which puae's core info " +
			"marks as required and which is not ours to ship.",
	},
	"dos": {
		Reason: reasonNeedsIsolation,
		Detail: "MS-DOS runs on dosbox_pure, which EmulatorJS publishes only " +
			"as a threaded build. Threads need SharedArrayBuffer, which needs " +
			"a cross-origin-isolated page, which this site is not.",
	},
	"psp": {
		Reason: reasonNeedsIsolation,
		Detail: "PSP runs on ppsspp, which EmulatorJS publishes only as a " +
			"threaded build. Threads need SharedArrayBuffer, which needs a " +
			"cross-origin-isolated page, which this site is not.",
	},
	// Arcade is refused for a different reason and it is worth naming plainly:
	// a MAME romset must match the MAME build that reads it, and archive.org's
	// `emulator` for an arcade item is the MAME *driver* name ("contra",
	// "mspacman"), not a machine. ROM Hub's archive-org plugin leaves ~60 of
	// those unmapped on purpose for the same reason. The Archive's own player
	// runs them with the build they were dumped for, so they route there.
	"mame": {
		Reason: reasonNoCore,
		Detail: "Arcade games need a romset built for the exact emulator " +
			"reading it. The Internet Archive's own player uses the build " +
			"these were prepared for; ours would not.",
	},
	"arcade": {
		Reason: reasonNoCore,
		Detail: "Arcade games need a romset built for the exact emulator " +
			"reading it. The Internet Archive's own player uses the build " +
			"these were prepared for; ours would not.",
	},
}

type blockedSystem struct {
	Reason string
	Detail string
}

// --- archive.org's emulator id -> a machine we can name and maybe run -------

type archivePlatform struct {
	// Core is the EmulatorJS system name, or "" when EmulatorJS has no core for
	// this machine at all. Empty is a first-class value, not a missing one.
	Core string
	// Platform is the library platform slug, in ROM Hub's vocabulary. Carried
	// even when Core is empty, because a caller wants to know WHICH machine it
	// cannot play, and because it is what the drift test keys on.
	Platform string
	// Label is what a person reads.
	Label string
}

// archivePlaySystems is the translation, and every row is an archive.org
// emulator id that the Archive actually uses.
//
// The ids were taken from ROM Hub's archive-org plugin (`platforms.py`), which
// sampled 2,000 live items and then censused all 132 distinct `emulator` values
// in the 24,746-item Console Living Room -- so they are what the corpus
// contains rather than what an emulator list suggests it might. Counts in the
// comments were measured against archive.org on 2026-08-07.
//
// Five ids in the shipped `ejsCores` table are NOT archive.org emulator ids and
// are absent here: `famicom`, `superfamicom`, `segaMD`, `gg` and `vb` each
// match exactly zero items. Six real ones the shipped table lacked are present:
// `megadrij`, `nesp`, `nespal`, `a2600p`, `snesp` and `sgx`, together about 195
// downloadable games that were never offered our player.
var archivePlaySystems = map[string]archivePlatform{
	// Nintendo.
	"nes":     {Core: "nes", Platform: "nes", Label: "NES"},
	"nesp":    {Core: "nes", Platform: "nes", Label: "NES"},    // PAL NES: a region, not a machine
	"nespal":  {Core: "nes", Platform: "nes", Label: "NES"},    // the same, spelled differently
	"snes":    {Core: "snes", Platform: "snes", Label: "SNES"}, // 348 downloadable
	"snesp":   {Core: "snes", Platform: "snes", Label: "SNES"},
	"gameboy": {Core: "gb", Platform: "gb", Label: "Game Boy"},
	// EmulatorJS has no `gbc` system -- gambatte serves both, under `gb`.
	// Writing `gbc` here is one of the four typos that browse fine and fail on
	// the button press.
	"gbcolor": {Core: "gb", Platform: "gbc", Label: "Game Boy Color"}, // 541 downloadable
	"gba":     {Core: "gba", Platform: "gba", Label: "Game Boy Advance"},
	// n64 is the one row here that ROM Hub's archive-org plugin does NOT have,
	// and it is a gap in the plugin rather than an invention here: the id is
	// real (8 items, all downloadable, .n64/.z64 payloads of 4-33 MB, measured
	// 2026-08-07), it simply never came up in a 2,000-item sample of 272,000.
	// It is worth a row upstream. Held to the same standard meanwhile: `n64` is
	// a RomM platform slug and `n64` is an EmulatorJS system, so both halves of
	// the chain still check out, and the exception is pinned by a test so it
	// cannot quietly become a habit.
	"n64": {Core: "n64", Platform: "n64", Label: "Nintendo 64"},

	// Sega. `genesis`, `megadriv` and `megadrij` are one machine under the
	// Archive's export/domestic/Japanese spellings; `sms`, `smsj` and
	// `sms-phaser` likewise.
	"genesis":    {Core: "segaMD", Platform: "genesis", Label: "Genesis"}, // 10,165 downloadable
	"megadriv":   {Core: "segaMD", Platform: "genesis", Label: "Mega Drive"},
	"megadrij":   {Core: "segaMD", Platform: "genesis", Label: "Mega Drive"},
	"32x":        {Core: "sega32x", Platform: "sega32", Label: "Sega 32X"},
	"sms":        {Core: "segaMS", Platform: "sms", Label: "Master System"},
	"smsj":       {Core: "segaMS", Platform: "sms", Label: "Master System"},
	"sms-phaser": {Core: "segaMS", Platform: "sms", Label: "Master System"},
	"gamegear":   {Core: "segaGG", Platform: "gamegear", Label: "Game Gear"},

	// Atari.
	"a2600":  {Core: "atari2600", Platform: "atari2600", Label: "Atari 2600"}, // 2,600 downloadable
	"a2600p": {Core: "atari2600", Platform: "atari2600", Label: "Atari 2600"},
	"a5200":  {Core: "atari5200", Platform: "atari5200", Label: "Atari 5200"},
	"a7800":  {Core: "atari7800", Platform: "atari7800", Label: "Atari 7800"},
	"lynx":   {Core: "lynx", Platform: "lynx", Label: "Atari Lynx"},

	// NEC. SuperGrafx runs on the same mednafen_pce core as the TurboGrafx-16
	// and is a separate machine and a separate slug, which is why both rows
	// exist rather than one folding into the other.
	"tg16": {Core: "pce", Platform: "tg16", Label: "TurboGrafx-16"}, // 312 downloadable
	"sgx":  {Core: "pce", Platform: "supergrafx", Label: "SuperGrafx"},

	// Bandai / SNK handhelds.
	"wswan":   {Core: "ws", Platform: "wonderswan", Label: "WonderSwan"},
	"wscolor": {Core: "ws", Platform: "wonderswan-color", Label: "WonderSwan Color"},
	"ngp":     {Core: "ngp", Platform: "neo-geo-pocket", Label: "Neo Geo Pocket"},
	"ngpc":    {Core: "ngp", Platform: "neo-geo-pocket-color", Label: "Neo Geo Pocket Color"},

	// Commodore. `vice-resid` is the single most common emulator id on
	// archive.org -- 98,081 items -- and none of them was ever offered our
	// player. VICE carries the machine's own ROMs inside the core, so unlike the
	// Amiga there is no firmware to be missing.
	"vice":       {Core: "c64", Platform: "c64", Label: "Commodore 64"},
	"vice-resid": {Core: "c64", Platform: "c64", Label: "Commodore 64"},
	"vice-c64":   {Core: "c64", Platform: "c64", Label: "Commodore 64"},
	"vice-vic20": {Core: "vic20", Platform: "vic-20", Label: "VIC-20"},
	"vice-pet":   {Core: "pet", Platform: "cpet", Label: "Commodore PET"},

	// Machines that reach a core we must still refuse. Kept in the table with a
	// Core set so the refusal can be specific -- "ColecoVision needs a BIOS"
	// rather than "we do not know what this is". blockedSystems supplies the
	// sentence.
	"coleco":      {Core: "coleco", Platform: "colecovision", Label: "ColecoVision"},
	"psx":         {Core: "psx", Platform: "psx", Label: "PlayStation"},
	"sae-a500":    {Core: "amiga", Platform: "amiga", Label: "Amiga"},
	"sae-a500p":   {Core: "amiga", Platform: "amiga", Label: "Amiga"},
	"sae-a1200":   {Core: "amiga", Platform: "amiga", Label: "Amiga"},
	"dosbox":      {Core: "dos", Platform: "dos", Label: "MS-DOS"},
	"dosbox-sync": {Core: "dos", Platform: "dos", Label: "MS-DOS"},
	"mame":        {Core: "mame", Platform: "arcade", Label: "Arcade"},

	// Machines EmulatorJS has no core for at all. Present with an empty Core so
	// the answer names the machine instead of shrugging: an Intellivision game
	// is refused as an Intellivision game. ROM Hub's `playability.NO_EQUIVALENT`
	// records, for each of these, why it was not quietly refiled under a
	// platform that does play -- which is the tempting and wrong fix.
	"intv":              {Platform: "intellivision", Label: "Intellivision"},
	"intv2":             {Platform: "intellivision", Label: "Intellivision"},
	"intvsrs":           {Platform: "intellivision", Label: "Intellivision"},
	"sg1000":            {Platform: "sg1000", Label: "SG-1000"},
	"vectrex":           {Platform: "vectrex", Label: "Vectrex"},
	"odyssey2":          {Platform: "odyssey-2", Label: "Odyssey 2"},
	"channelf":          {Platform: "fairchild-channel-f", Label: "Fairchild Channel F"},
	"arcadia":           {Platform: "arcadia-2001", Label: "Arcadia 2001"},
	"gamecom":           {Platform: "game-dot-com", Label: "Game.com"},
	"svision":           {Platform: "supervision", Label: "Watara Supervision"},
	"megaduck":          {Platform: "mega-duck-slash-cougar-boy", Label: "Mega Duck"},
	"supracan":          {Platform: "super-acan", Label: "Super A'Can"},
	"scv":               {Platform: "epoch-super-cassette-vision", Label: "Super Cassette Vision"},
	"crvision":          {Platform: "creativision", Label: "CreatiVision"},
	"advision":          {Platform: "adventure-vision", Label: "Adventure Vision"},
	"gx4000":            {Platform: "amstrad-gx4000", Label: "Amstrad GX4000"},
	"cpc6128":           {Platform: "acpc", Label: "Amstrad CPC"},
	"spectrum":          {Platform: "zxs", Label: "ZX Spectrum"},
	"spec128":           {Platform: "zxs", Label: "ZX Spectrum 128K"},
	"zx81":              {Platform: "zx81", Label: "ZX81"},
	"a800":              {Platform: "atari8bit", Label: "Atari 8-bit"},
	"a800xl":            {Platform: "atari8bit", Label: "Atari 8-bit"},
	"a800xlp":           {Platform: "atari8bit", Label: "Atari 8-bit"},
	"a800cart":          {Platform: "atari8bit", Label: "Atari 8-bit"},
	"apple2":            {Platform: "appleii", Label: "Apple II"},
	"apple2e":           {Platform: "appleii", Label: "Apple II"},
	"apple2ee":          {Platform: "appleii", Label: "Apple II"},
	"apple2ee-helper":   {Platform: "appleii", Label: "Apple II"},
	"apple2eeecho":      {Platform: "appleii", Label: "Apple II"},
	"apple2p":           {Platform: "appleii", Label: "Apple II"},
	"apple2woz":         {Platform: "appleii", Label: "Apple II"},
	"apple2gs":          {Platform: "apple-iigs", Label: "Apple IIgs"},
	"apple3":            {Platform: "appleiii", Label: "Apple III"},
	"aquarius":          {Platform: "aquarius", Label: "Mattel Aquarius"},
	"mc10":              {Platform: "trs-80-mc-10", Label: "TRS-80 MC-10"},
	"coco2cart":         {Platform: "trs-80-color-computer", Label: "TRS-80 CoCo"},
	"coco2disk":         {Platform: "trs-80-color-computer", Label: "TRS-80 CoCo"},
	"coco3disk":         {Platform: "trs-80-color-computer", Label: "TRS-80 CoCo"},
	"pce-macplus":       {Platform: "mac", Label: "Macintosh"},
	"vmac-colormac":     {Platform: "mac", Label: "Macintosh"},
	"pce-atarist":       {Platform: "atari-st", Label: "Atari ST"},
	"pce-atarist-color": {Platform: "atari-st", Label: "Atari ST"},
}

// --- what the caller is told -----------------------------------------------

// playReason is one sentence about why something was refused, plus a code a
// client can branch on without reading English.
type playReason struct {
	Code   string `json:"code"`
	Detail string `json:"detail"`
}

// playROM is the file, and only ever appears when it is actually fetchable.
type playROM struct {
	Name string `json:"name"`
	// URL is what the player loads: the relay, because archive.org sends no
	// Access-Control-Allow-Origin on downloads and a WASM emulator fetches the
	// ROM itself.
	URL string `json:"url"`
	// Direct is the same file at archive.org, so a caller that is not a browser
	// (a native client, a test) can skip the relay and cost us nothing. EMPTY
	// for an item the Archive marks stream-only: playing it is permitted and
	// handing somebody the file is what is not.
	Direct    string `json:"direct,omitempty"`
	SizeBytes int64  `json:"sizeBytes"`
}

type playAnswer struct {
	ID    string `json:"id"`
	Title string `json:"title,omitempty"`

	// Domain and Type come from schema.json's frozen game vocabulary. An item
	// on archive.org is a concrete dump of one game for one machine, which is a
	// "release", not the abstract "game" -- the same call provider_romm.go makes
	// for a RomM ROM.
	Domain string `json:"domain"`
	Type   string `json:"type"`

	// Emulator is archive.org's own id, carried verbatim so a refusal can name
	// it and somebody can look it up.
	Emulator string `json:"emulator,omitempty"`
	Platform string `json:"platform,omitempty"`
	System   string `json:"system,omitempty"`

	// Playable is the whole point, and it means "pressing Play produces a
	// game", by either route.
	Playable bool   `json:"playable"`
	Route    string `json:"route"`

	// Core is the EmulatorJS system name, present only on the emulatorjs route.
	Core string `json:"core,omitempty"`
	// CoreFile is the core EmulatorJS will download for that system. Carried so
	// the claim is checkable rather than asserted -- a name that is valid and a
	// core that is published are different things.
	CoreFile string   `json:"coreFile,omitempty"`
	ROM      *playROM `json:"rom,omitempty"`

	// Embed is the Internet Archive's own player, present whenever the item
	// declares an emulator -- including on the emulatorjs route, so a client can
	// offer it as the fallback when a phone's memory will not hold a core.
	// It is what makes the player switch possible: two routes, both real.
	Embed string `json:"embed,omitempty"`

	// BiosNeeded is set when firmware is the ONLY thing between this item and
	// our own player. It is an invitation rather than an error: the file is not
	// ours to ship and is the console owner's to supply, so naming it turns a
	// refusal into an instruction. Absent when the item would fail for some
	// other reason too, because offering somebody a way to unblock a game that
	// would then be refused for its size is a worse lie than saying no.
	BiosNeeded *playBIOS `json:"biosNeeded,omitempty"`

	// Guide is what the game is and which key is fire. See play_guide.go.
	Guide *playGuide `json:"guide,omitempty"`

	// Touch says whether the offered route has on-screen controls. Their player
	// expects a keyboard, so on a phone a console game there is something you
	// can watch and not play; that is a caveat about the route, not a lie about
	// whether it plays.
	Touch bool `json:"touch"`

	// StreamOnly carries the Internet Archive's own "play but do not download"
	// marker. It is NOT a refusal and never affects the route: it is a fact
	// about what a client may offer to do with the file, and the one thing it
	// forbids -- publishing a direct link -- is already done by leaving
	// ROM.Direct empty.
	StreamOnly bool `json:"streamOnly,omitempty"`

	// Reasons is never empty unless Route is emulatorjs. Every downgrade and
	// every refusal is named here, in the order they were found, so a UI can be
	// honest without inventing an explanation of its own.
	Reasons []playReason `json:"reasons,omitempty"`
}

// directIfDownloadable withholds the direct link for an item the Archive marks
// stream-only. One line, in one place, so "play yes, download no" cannot be
// half-implemented.
func directIfDownloadable(direct string, streamOnly bool) string {
	if streamOnly {
		return ""
	}
	return direct
}

// --- archive.org metadata ---------------------------------------------------

// Only the fields this decision turns on, and three of them are RawMessage
// because archive.org genuinely sends more than one shape for each:
//
//	size            a decimal STRING, or absent entirely
//	collection      a list, except when the item is in exactly one, where
//	                it is a bare string
//	emulator_ext    a string, except when an item ships more than one
//	                playable form, where it is a list -- `f-zero-x-usa_202506`
//	                declares ["zip","z64"]
//
// The last one is not a curiosity. Declaring it as a `string` makes the whole
// decode fail on that item, and a decode failure reads as "the Archive did not
// answer" -- so one unusual item would be reported as an outage.
type playItemMetadata struct {
	Metadata struct {
		Identifier  string          `json:"identifier"`
		Title       string          `json:"title"`
		MediaType   string          `json:"mediatype"`
		Emulator    string          `json:"emulator"`
		EmulatorExt json.RawMessage `json:"emulator_ext"`
		Collection  json.RawMessage `json:"collection"`
		AccessRestr json.RawMessage `json:"access-restricted-item"`

		// The three fields the guide is built from. `emulator_instructions` is
		// the Archive's own per-game control notes and is the single most
		// valuable field on the whole item -- measured live 2026-08-07, River
		// Raid's says which key is fire. `controller` is "joystick", "keyboard"
		// or "paddle". See play_guide.go.
		//
		// All three are RawMessage for the reason emulator_ext is: archive.org
		// sends a bare string when there is one value and a list when there is
		// more than one, and an item with two descriptions must not decode as an
		// outage. That trap has already been paid for once in this file.
		Description          json.RawMessage `json:"description"`
		EmulatorInstructions json.RawMessage `json:"emulator_instructions"`
		Controller           json.RawMessage `json:"controller"`
	} `json:"metadata"`
	Files []struct {
		Name   string `json:"name"`
		Format string `json:"format"`
		Size   string `json:"size"`
	} `json:"files"`
}

// jsonStrings reads a field archive.org sends as either one string or a list
// of them. Empty means the field was absent or unusable, which callers must
// treat as "the Archive did not say" rather than as a default.
func jsonStrings(raw json.RawMessage) []string {
	if len(raw) == 0 {
		return nil
	}
	var list []string
	if err := json.Unmarshal(raw, &list); err == nil {
		out := make([]string, 0, len(list))
		for _, s := range list {
			if s = strings.TrimSpace(s); s != "" {
				out = append(out, s)
			}
		}
		return out
	}
	var one string
	if err := json.Unmarshal(raw, &one); err == nil {
		if one = strings.TrimSpace(one); one != "" {
			return []string{one}
		}
	}
	return nil
}

// extensions is what the Archive says the payload is, normalised. In declared
// order, because when an item offers several the Archive's own ordering is the
// only preference anyone has stated.
func (m *playItemMetadata) extensions() []string {
	raw := jsonStrings(m.Metadata.EmulatorExt)
	out := make([]string, 0, len(raw))
	for _, ext := range raw {
		ext = strings.ToLower(strings.TrimPrefix(strings.TrimSpace(ext), "."))
		if ext != "" {
			out = append(out, ext)
		}
	}
	return out
}

// collections reads archive.org's `collection`, which is a list of strings
// except when the item is in exactly one, where it is a bare string.
func (m *playItemMetadata) collections() []string {
	return jsonStrings(m.Metadata.Collection)
}

// streamOnly reports the Archive's own "you may play this but not download it"
// marker.
//
// This is a POLICY signal and is treated as one. The bytes are in fact served
// -- measured: a stream-only Game Gear ROM downloads with HTTP 200 -- so this is
// not a technical failure we are reporting but a restriction we are honouring.
// Relaying such a file would republish it from our host, which is precisely what
// the marker asks us not to do. ROM Hub's importer refuses on the same signal
// for the same reason.
//
// Both spellings are read because both appear: the `stream_only` collection and
// `access-restricted-item`. On every item sampled they agree, and taking either
// as sufficient means a future item that carries only one is still honoured.
func (m *playItemMetadata) streamOnly() bool {
	for _, c := range m.collections() {
		if strings.EqualFold(strings.TrimSpace(c), "stream_only") {
			return true
		}
	}
	if len(m.Metadata.AccessRestr) > 0 {
		var s string
		if err := json.Unmarshal(m.Metadata.AccessRestr, &s); err == nil {
			return strings.EqualFold(strings.TrimSpace(s), "true")
		}
		var b bool
		if err := json.Unmarshal(m.Metadata.AccessRestr, &b); err == nil {
			return b
		}
	}
	return false
}

// payload picks the file that is the game.
//
// The rule is ROM Hub's importer's, and it is the Archive's own assertion
// rather than our guess: `emulator_ext` names the payload extension, and among
// the files that match it the largest wins with a missing size sorting last, so
// a metadata stub can never outrank the actual game. The name breaks ties, so
// the same item always resolves to the same file.
//
// Deliberately NOT the browser's `bestFile` heuristic. That works, but it works
// by knowing a list of ROM extensions -- and `.bin` is ColecoVision, Atari 2600,
// Mega Drive and PC Engine at once. Where the Archive has told us which file it
// is, asking is better than inferring.
// When the Archive declares several extensions they are tried in the order it
// declared them, and the first that matches any file wins. That ordering is the
// only preference anybody has stated, and preferring one ourselves -- biggest,
// or "the one that is not a zip" -- would be us overruling the source about its
// own item.
func (m *playItemMetadata) payload() (name string, size int64, ok bool) {
	for _, ext := range m.extensions() {
		suffix := "." + ext
		best, bestSize := "", int64(-1)
		for _, f := range m.Files {
			if !strings.HasSuffix(strings.ToLower(f.Name), suffix) {
				continue
			}
			// A bare ".zip" has no basename; there is nothing to name or fetch.
			if base := path.Base(f.Name); base == "" || base == suffix {
				continue
			}
			size := parseArchiveSize(f.Size)
			if size > bestSize || (size == bestSize && f.Name < best) {
				best, bestSize = f.Name, size
			}
		}
		if best == "" {
			continue
		}
		if bestSize < 0 {
			bestSize = 0
		}
		return best, bestSize, true
	}
	return "", 0, false
}

// parseArchiveSize reads `files[].size`, which is a decimal string or absent.
// Absent is -1 rather than 0 so it sorts below every real size.
func parseArchiveSize(raw string) int64 {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return -1
	}
	var n int64
	if _, err := fmt.Sscanf(raw, "%d", &n); err != nil || n < 0 {
		return -1
	}
	return n
}

// --- the decision -----------------------------------------------------------

// playArchive answers "can this be played, and how".
type playArchive struct {
	client *http.Client
	// metadataBase is where item metadata is read from. A field so a test can
	// point it at a local server; there is no other reason to change it.
	metadataBase string
	downloadBase string
	embedBase    string

	// firmware is the household's own library, if it has one. nil is a
	// first-class value: every path that touches it degrades to the next source
	// and finally to the bring-your-own offer, which is what this endpoint did
	// before there was anything to ask. See play_bios.go.
	firmware biosLibrary
	// diskFirmware is the operator's own firmware directory on this machine,
	// when they have one and this service can see it. nil on the hosted
	// instance, which cannot see anybody's disk and does not pretend to.
	diskFirmware biosLibrary
	// publicFirmware is the Internet Archive's own player's firmware, relayed.
	// It needs no configuration and no credential, so unlike the line above it
	// is present by default. See play_bios_archive.go.
	publicFirmware biosLibrary
}

func newPlayArchive(client *http.Client) *playArchive {
	if client == nil {
		client = &http.Client{Timeout: playMetadataTimeout}
	}
	return &playArchive{
		client:       client,
		metadataBase: "https://archive.org/metadata/",
		downloadBase: "https://archive.org/download/",
		embedBase:    "https://archive.org/embed/",
		// Both firmware sources are left nil here and wired in
		// registerPlayRoutes. A constructor that reached the network by default
		// would make every test that builds one reach the network too, and a
		// test suite that quietly depends on archive.org being up is a suite
		// that fails for reasons that have nothing to do with the change.
	}
}

// registerPlayRoutes wires the play endpoints.
//
// Both are catalogue data in the sense cors.go draws the line: they describe
// what exists on archive.org and reveal nothing about this household, so a
// television or somebody else's client must be able to read them from another
// origin. They spend no disk and no relay bandwidth -- resolving costs one
// metadata request, and the ROM bytes only ever move when a player actually
// fetches the URL through /bridge/iptv, which has its own budget and its own
// concurrency gate.
//
// If the operator wants these behind the same reader gate as /api/pages, wrap
// them the way main.go wraps that one; nothing here depends on being open.
func registerPlayRoutes(mux *http.ServeMux) {
	p := newPlayArchive(nil)

	// The firmware the Internet Archive's own player uses. Unconditional,
	// because it needs nothing from anybody: no credential, no setting, no
	// file, and no operator who knew to configure it. A household with no
	// library server still gets a ColecoVision that plays, which is the whole
	// point of it being here.
	p.publicFirmware = newArchiveFirmware(nil)

	// The operator's own firmware tree, if this service can see one. A
	// self-hoster's whole collection with one environment variable and no
	// import step; absent on the hosted instance, which has no such disk.
	if dir := newDirFirmwareFromEnv(); dir != nil {
		p.diskFirmware = dir
		// Read once at startup, off the request path, so the first person to
		// open a ColecoVision item is not the one who discovers the tree.
		go dir.Firmware(context.Background(), "coleco")
	}

	// The household's own firmware, from the RomM the operator has already
	// configured. nil when there is none, and everything below is written so
	// that nil is simply the way it worked yesterday.
	if lib := newRommFirmwareFromEnv(); lib != nil {
		p.firmware = lib
		// Built once, off the request path, so the first person to open a
		// ColecoVision item is not the one who discovers the library. A failure
		// here costs nothing: the next real verdict asks again.
		go func() {
			ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
			defer cancel()
			lib.Warm(ctx)
		}()
	}
	p.register(mux)
}

func (p *playArchive) register(mux *http.ServeMux) {
	mux.HandleFunc("/api/play/archive", publicCORS(p.handleArchive))
	mux.HandleFunc("/api/play/systems", publicCORS(p.handleSystems))
	// One firmware file per machine per source, relayed. The method is pinned
	// because this is a read and nothing else; every path value is checked
	// against an index that was built elsewhere rather than used to address
	// anything, so this is not a proxy.
	mux.HandleFunc("GET /api/play/bios/{source}/{system}/{file}", publicCORS(p.handleBIOS))
	mux.HandleFunc("HEAD /api/play/bios/{source}/{system}/{file}", publicCORS(p.handleBIOS))
}

// playOptions are the things only the CALLER can know, because they are facts
// about the browser asking rather than about the item.
//
// Both of them turn a refusal into a game, and neither can be guessed from here:
// a BIOS lives in one visitor's browser storage and nowhere else, and whether a
// page is cross-origin isolated is a property of the document that loaded, not
// of this server. Defaulting both to the pessimistic value is deliberate -- an
// answer computed without them is the answer for a visitor who has neither, and
// that is the one that must never be optimistic.
type playOptions struct {
	// BIOS is the set of EmulatorJS system names the caller holds firmware for.
	BIOS map[string]bool
	// Isolated is `crossOriginIsolated` in the calling document. When true,
	// SharedArrayBuffer exists and the threaded cores (DOS, PSP) can run.
	Isolated bool
}

func (o playOptions) hasBIOS(core string) bool {
	return o.BIOS != nil && o.BIOS[core]
}

// parsePlayOptions reads the two capability declarations off the query string.
//
// A DECLARATION, not a promise: a client claiming a BIOS it does not have gets
// our player and a game that will not boot, which is its own doing and its own
// to fix. Nothing here is trusted with anything but the answer to "which button
// do I draw", and being wrong costs that client one click.
func parsePlayOptions(q url.Values) playOptions {
	opts := playOptions{Isolated: q.Get("isolated") == "1"}
	for _, field := range q["bios"] {
		for _, name := range strings.Split(field, ",") {
			name = strings.TrimSpace(name)
			if name == "" {
				continue
			}
			if _, known := biosRequirements[name]; !known {
				// Only the three machines that are actually blocked on firmware
				// can be unblocked by it. Accepting an arbitrary name would let
				// a typo look like a capability.
				continue
			}
			if opts.BIOS == nil {
				opts.BIOS = map[string]bool{}
			}
			opts.BIOS[name] = true
		}
	}
	return opts
}

// handleArchive resolves one item.
func (p *playArchive) handleArchive(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	id := archiveIdentifier(q.Get("id"))
	if id == "" {
		writeJSON(w, http.StatusBadRequest, map[string]string{
			"error": "id is required: an archive.org identifier, or any archive.org item URL",
		})
		return
	}
	writeJSON(w, http.StatusOK, p.ResolveWith(r.Context(), id, parsePlayOptions(q)))
}

// handleSystems publishes the table.
//
// It exists so a client can decide whether to draw a Play affordance at all
// before spending a metadata request -- a search result already carries its
// platform -- and so the refusals are inspectable by somebody who wants to know
// why their favourite machine is not offered, without reading this file.
func (p *playArchive) handleSystems(w http.ResponseWriter, r *http.Request) {
	type systemView struct {
		Emulator string `json:"emulator"`
		Platform string `json:"platform"`
		System   string `json:"system"`
		Core     string `json:"core,omitempty"`
		CoreFile string `json:"coreFile,omitempty"`
		Playable bool   `json:"playable"`
		Reason   string `json:"reason,omitempty"`
		Detail   string `json:"detail,omitempty"`
		// Unlockable says the refusal is about this visitor rather than about
		// this machine, and names what would lift it. It is what lets a client
		// draw a "add your ColecoVision BIOS" screen without a second table of
		// which machines that could possibly apply to.
		Unlockable string    `json:"unlockable,omitempty"`
		BIOS       *playBIOS `json:"bios,omitempty"`
	}
	out := make([]systemView, 0, len(archivePlaySystems))
	for emulator, plat := range archivePlaySystems {
		v := systemView{
			Emulator: emulator, Platform: plat.Platform, System: plat.Label,
		}
		switch {
		case plat.Core == "":
			v.Reason = reasonNoCore
			v.Detail = noCoreDetail(plat)
		case blockedSystems[plat.Core].Reason != "":
			b := blockedSystems[plat.Core]
			v.Reason, v.Detail = b.Reason, b.Detail
			switch b.Reason {
			case reasonNeedsBIOS:
				if need, ok := biosRequirements[plat.Core]; ok {
					v.Unlockable, v.BIOS = "bios", &need
				}
			case reasonNeedsIsolation:
				v.Unlockable = "isolation"
			}
			// The core is named ONLY when it could actually be used -- i.e.
			// when the refusal is liftable. Arcade is refused for a reason no
			// visitor can lift, and publishing `mame2003_plus` beside that
			// refusal would advertise a core this endpoint will never choose.
			if v.Unlockable != "" {
				v.Core = plat.Core
				v.CoreFile = emulatorJSSystems[plat.Core]
			}
		default:
			v.Playable = true
			v.Core = plat.Core
			v.CoreFile = emulatorJSSystems[plat.Core]
		}
		out = append(out, v)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Emulator < out[j].Emulator })

	// Every machine a visitor could unblock by supplying firmware, listed once
	// rather than once per emulator id, so a settings screen has something to
	// iterate that is not the 90-row table above.
	biosList := make([]playBIOS, 0, len(biosRequirements))
	for _, need := range biosRequirements {
		biosList = append(biosList, need)
	}
	sort.Slice(biosList, func(i, j int) bool { return biosList[i].System < biosList[j].System })

	writeJSON(w, http.StatusOK, map[string]any{
		"domain":  "game",
		"type":    "release",
		"systems": out,
		"bios":    biosList,
		// The ceiling is part of the contract: a client that knows it can say
		// "too big to play here" about a file it already has the size of.
		"maxRelayBytes": maxRelayROMBytes,
	})
}

// Resolve answers for a visitor who has declared nothing -- no BIOS, no
// cross-origin isolation. That is the conservative answer and the right default:
// every capability below only ever turns a `no` into a `yes`, so an answer
// computed without them can be too pessimistic and never too optimistic.
func (p *playArchive) Resolve(ctx context.Context, id string) playAnswer {
	return p.ResolveWith(ctx, id, playOptions{})
}

// ResolveWith is the whole decision, and it is ordered so that the reason a
// person is given is the FIRST thing that is wrong rather than the last check to
// run.
func (p *playArchive) ResolveWith(ctx context.Context, id string, opts playOptions) playAnswer {
	answer := playAnswer{ID: id, Domain: "game", Type: "release", Route: routeNone}

	meta, err := p.metadata(ctx, id)
	if err != nil {
		answer.Reasons = append(answer.Reasons, playReason{
			Code:   reasonUpstream,
			Detail: "the Internet Archive did not answer for this item, so whether it plays is unknown.",
		})
		return answer
	}
	if meta.Metadata.Identifier == "" && meta.Metadata.Title == "" && len(meta.Files) == 0 {
		// A 200 carrying `{}` is how archive.org answers for an identifier that
		// does not exist.
		answer.Reasons = append(answer.Reasons, playReason{
			Code:   reasonNotFound,
			Detail: "the Internet Archive has no item with this identifier.",
		})
		return answer
	}
	answer.Title = strings.TrimSpace(meta.Metadata.Title)

	// The guide is attached HERE, before any refusal, and it is attached on
	// every path from this point on. A person sent to the Archive's own player
	// needs the instructions at least as much as one who got ours -- more,
	// because that player has no on-screen pad to experiment with -- and an item
	// that plays nowhere is still a game somebody may want to read about.
	plat, known := archivePlaySystems[strings.ToLower(strings.TrimSpace(meta.Metadata.Emulator))]
	answer.Guide = p.guideFor(meta, plat.Core, plat.Label)

	// 1. Does the Archive itself say this is an emulated item? Their `emulator`
	//    field IS the definition of "runs in a browser here", not a proxy for
	//    it. Nothing is guessed from a filename: that is what boots a
	//    ColecoVision game as an NES.
	emulator := strings.TrimSpace(meta.Metadata.Emulator)
	if emulator == "" {
		answer.Reasons = append(answer.Reasons, playReason{
			Code: reasonNotEmulated,
			Detail: "this item is not an emulated one -- the Internet Archive " +
				"declares no emulator for it, so there is nothing to run.",
		})
		return answer
	}
	answer.Emulator = emulator

	// From here the Archive's own player can run it, so `none` is off the table
	// and the worst outcome is `archive`.
	answer.Embed = p.embedBase + url.PathEscape(id)

	answer.Platform, answer.System = plat.Platform, plat.Label

	// 2. Do we know the machine, and is there a core for it?
	switch {
	case !known:
		return p.viaArchive(answer, playReason{
			Code: reasonNoCore,
			Detail: fmt.Sprintf(
				"the Internet Archive runs this on %q, which is not a machine "+
					"this player has a core for. Their own player will run it.",
				emulator),
		})
	case plat.Core == "":
		return p.viaArchive(answer, playReason{
			Code: reasonNoCore, Detail: noCoreDetail(plat),
		})
	}

	// 3. Is the core one that cannot work in an ordinary tab? A missing BIOS is
	//    the dangerous case: the emulator starts, draws its own error screen and
	//    streams it at a healthy frame rate, so nothing downstream can tell that
	//    from a working game.
	//
	//    Two of the three reasons a core is blocked are not facts about the core
	//    at all -- they are facts about the visitor, and the visitor can change
	//    them. Firmware we may not ship is firmware its owner may supply; a page
	//    that is not cross-origin isolated is a page that could be. Where the
	//    caller has declared the missing piece, the block does not apply, and
	//    where it has not, the answer names what would lift it.
	//    Firmware now has TWO possible owners and exactly one code path. A file
	//    the visitor added by hand and a file the household's library already
	//    holds unblock the machine identically; all that differs is where the
	//    client fetches the bytes, which is the last thing decided and the only
	//    thing carried out. Asked once, here, so the refusal branch and the
	//    success branch can never disagree about whether firmware was available.
	bios := p.firmwareFor(ctx, plat.Core, opts)
	if b, blocked := blockedSystems[plat.Core]; blocked && !p.unblocked(b, plat.Core, opts, bios != nil) {
		if need, ok := biosRequirements[plat.Core]; ok && b.Reason == reasonNeedsBIOS {
			// Named only when firmware really is the last obstacle. See the
			// field comment: pointing somebody at a 460 MB disc image's BIOS is
			// a longer route to the same refusal, and the refusal would arrive
			// after they had gone and found the file.
			// Stream-only is no longer part of this: such an item plays here
			// perfectly well, so firmware really is the last obstacle for it.
			_, size, hasPayload := meta.payload()
			if hasPayload && size <= maxRelayROMBytes {
				answer.BiosNeeded = &need
			}
		}
		return p.viaArchive(answer, playReason{Code: b.Reason, Detail: b.Detail})
	}

	// 4. What the Archive's stream-only marker actually asks for.
	//
	//    It used to send the item to their player, and that was wrong. The
	//    distinction the Archive draws is PLAY YES, DOWNLOAD NO -- and their own
	//    Emularity player fetches the ROM into the browser's memory to run it,
	//    which is precisely what ours does. Refusing to run it here did not
	//    honour anything; it just meant the same act happened on their page
	//    instead of ours, on a player with no touch controls.
	//
	//    So the marker is carried rather than obeyed as a refusal, and it is
	//    obeyed where it means something: no direct link is published for a
	//    stream-only item, so there is nothing to save and nothing to hand on.
	//    That is the line that matters, and it costs nothing -- nobody wants a
	//    download button on a game they are already playing.
	//
	//    (The bytes were never the obstacle: a stream-only Game Gear ROM was
	//    measured downloading with HTTP 200. This was always a policy signal.)
	streamOnly := meta.streamOnly()

	// 5. Is there actually a file to play?
	name, size, ok := meta.payload()
	if !ok {
		detail := fmt.Sprintf(
			"this item declares no file for %s to load, so there is nothing to "+
				"hand the emulator.", plat.Label)
		if exts := meta.extensions(); len(exts) > 0 {
			detail = fmt.Sprintf(
				"this item names %q as its payload but has no file with that "+
					"extension, so there is nothing to hand the emulator.",
				strings.Join(exts, ", "))
		}
		return p.viaArchive(answer, playReason{Code: reasonNoPayload, Detail: detail})
	}

	// 6. Is it small enough to be worth relaying?
	if size > maxRelayROMBytes {
		return p.viaArchive(answer, playReason{
			Code: reasonTooLarge,
			Detail: fmt.Sprintf(
				"%s is %s, past the %s this relay will carry for one game -- a "+
					"disc image rather than a cartridge. Their player streams it "+
					"instead.",
				path.Base(name), humanBytes(size), humanBytes(maxRelayROMBytes)),
		})
	}

	direct := p.downloadBase + url.PathEscape(id) + "/" + archiveFilePath(name)
	answer.StreamOnly = streamOnly
	answer.Playable = true
	answer.Route = routeEmulatorJS
	answer.Core = plat.Core
	answer.CoreFile = emulatorJSSystems[plat.Core]
	answer.Touch = true
	// Carried on the way OUT as well as on the way in: this route was reached
	// because firmware was available, and the client has to know WHICH file to
	// hand the emulator and where to get it. Without this it would have to
	// re-derive the mapping from `core`, which is a second copy of a table.
	if need, ok := biosRequirements[plat.Core]; ok && bios != nil {
		need.Source, need.File, need.URL, need.SizeBytes, need.Options =
			bios.Source, bios.Name, bios.URL, bios.Size, bios.Options
		if bios.Detail != "" {
			// The generic sentence is an invitation to supply a file. Where
			// nobody has to, it would be describing something that is not
			// happening.
			need.Detail = bios.Detail
		}
		answer.BiosNeeded = &need
	}
	answer.ROM = &playROM{
		Name: path.Base(name),
		URL:  "/bridge/iptv?u=" + url.QueryEscape(direct),
		// Direct is the file at archive.org, for a caller that is not a browser
		// and can skip our relay -- and it is WITHHELD for a stream-only item,
		// because a direct link is exactly the download the Archive asks us not
		// to offer. The relay URL still works: that is the play, not the
		// download, and it is fetched by the emulator rather than by a person.
		Direct:    directIfDownloadable(direct, streamOnly),
		SizeBytes: size,
	}
	return answer
}

// unblocked reports whether the one missing thing has been supplied.
//
// `haveBIOS` is the answer for BOTH owners of firmware -- the visitor's own file
// and the household library's -- decided once by firmwareFor and passed in, so
// there is one condition here rather than two that could drift apart.
//
// Only two of the three block reasons can be lifted this way, and the third is
// the interesting one: `no_core` -- arcade -- stays blocked whatever anybody
// declares or holds, because a MAME romset must match the build reading it and
// no firmware changes that. Enumerating the liftable reasons rather than
// defaulting to "lift it" is what keeps that true if a fourth reason is added.
func (p *playArchive) unblocked(b blockedSystem, core string, opts playOptions, haveBIOS bool) bool {
	switch b.Reason {
	case reasonNeedsBIOS:
		return haveBIOS
	case reasonNeedsIsolation:
		return opts.Isolated
	default:
		return false
	}
}

// viaArchive downgrades to the Internet Archive's own player, carrying the
// reason. It is still Playable: their Emularity player is a real game in a real
// browser, and calling it unplayable would be its own dishonesty.
func (p *playArchive) viaArchive(answer playAnswer, reason playReason) playAnswer {
	answer.Playable = true
	answer.Route = routeArchive
	// Their player expects a keyboard and offers no on-screen pad. That is the
	// one thing a phone needs to know before it is told this "plays".
	answer.Touch = false
	answer.Reasons = append(answer.Reasons, reason)
	return answer
}

// noCoreDetail names the machine rather than shrugging. ROM Hub's
// playability.NO_EQUIVALENT records, for each of these, why it was not refiled
// under a platform that does play -- a temptation that is always available and
// always wrong.
func noCoreDetail(plat archivePlatform) string {
	name := plat.Label
	if name == "" {
		name = plat.Platform
	}
	if name == "" {
		return "there is no browser emulator core for this machine. The " +
			"Internet Archive's own player will run it."
	}
	return fmt.Sprintf(
		"there is no browser emulator core for the %s, and no other machine's "+
			"core will run its software. The Internet Archive's own player will "+
			"run it.", name)
}

// metadata fetches one item.
func (p *playArchive) metadata(ctx context.Context, id string) (*playItemMetadata, error) {
	ctx, cancel := context.WithTimeout(ctx, playMetadataTimeout)
	defer cancel()

	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		p.metadataBase+url.PathEscape(id), nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", "yarr.it/1.0 (+https://yarrit.com)")

	resp, err := p.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("archive.org metadata %s: status %d", id, resp.StatusCode)
	}

	var m playItemMetadata
	if err := json.NewDecoder(resp.Body).Decode(&m); err != nil {
		// Rate limiting and maintenance pages both arrive as 200 + HTML, so a
		// decode failure is an upstream problem rather than a missing item.
		return nil, fmt.Errorf("archive.org metadata %s: %w", id, err)
	}
	return &m, nil
}

// archiveFilePath escapes a filename for a URL path without escaping the
// slashes that separate directories inside an item.
func archiveFilePath(name string) string {
	parts := strings.Split(name, "/")
	for i, part := range parts {
		parts[i] = url.PathEscape(part)
	}
	return strings.Join(parts, "/")
}

// humanBytes renders a size the way a sentence wants it.
func humanBytes(n int64) string {
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := int64(unit), 0
	for m := n / unit; m >= unit && exp < 3; m /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %ciB", float64(n)/float64(div), "KMGT"[exp])
}
